DROP TABLE IF EXISTS ICD10_SCHEME;
CREATE TABLE ICD10_SCHEME (
  NAME varchar(40) NOT NULL,
  VERSION varchar(20) NOT NULL,
  DATE varchar(10) NOT NULL,
  AUTHORITY varchar(45) NOT NULL,
  UID varchar(60) NOT NULL,
  LANG varchar(2) NOT NULL,
  TITLE varchar(255) NOT NULL,
  PRIMARY KEY (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES ICD10_SCHEME WRITE;
INSERT INTO ICD10_SCHEME VALUES ('ICD-10-EN_2019','2019','2020-03-22', 'WHO', 'icd10_2019', 'en', 'International Statistical Classification of Diseases and Related Health Problems 10th Revision');
UNLOCK TABLES;

DROP TABLE IF EXISTS ICD10_CLASS;
CREATE TABLE ICD10_CLASS (
  SEQ int(5) NOT NULL,
  CODE varchar(10) NOT NULL,
  VERSION varchar(4) NOT NULL,
  CLASS_KIND varchar(10) NOT NULL,
  USAGE_KIND varchar(10) DEFAULT NULL,
  SUPER_CLASS varchar(10) DEFAULT NULL,
  LABEL varchar(1000) NOT NULL,
  REF varchar(50) DEFAULT NULL,
  CHILDREN_COUNT int(4) DEFAULT NULL,
  DESCENDANT_COUNT int (4) DEFAULT NULL,
  PATH varchar(255) DEFAULT NULL,
  PRIMARY KEY (CODE, VERSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP  TABLE IF EXISTS ICD10_RUBRIC;
CREATE TABLE ICD10_RUBRIC (
  SEQ int(5) NOT NULL,
  CODE varchar(10) NOT NULL,
  VERSION varchar(4) NOT NULL,
  ID varchar(50) NOT NULL,
  KIND varchar(15) NOT NULL,
  MODIFIER_CODE varchar(10) DEFAULT NULL,
  USAGE_KIND varchar(10) DEFAULT NULL,
  LANG varchar(2) DEFAULT NULL,
  FRAGMENT_TYPE varchar(10) DEFAULT NULL,
  PARA_TYPE varchar(30) DEFAULT NULL,
  LABEL varchar(1000) NOT NULL,
  REF varchar(50) DEFAULT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#DROP TABLE IF EXISTS ICD10_META;
#CREATE TABLE ICD10_META (
#  CODE varchar(11) NOT NULL,
#  NAME varchar(10) DEFAULT NULL,
#  VALUE varchar(5) DEFAULT NULL,
#  PRIMARY KEY (CODE)
#) ENGINE=InnoDB DEFAULT CHARSET=utf8;
