-- 1303956008, NCPT Release Package
\! echo 'Loading NCPT CONCEPT Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NCPTRelease_PRODUCTION_20240412T120000Z/Full/Terminology/sct2_Concept_NCPTFull_INT_20240101.txt'
 INTO TABLE CONCEPT
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (CONCEPT_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, DEFINITION_STATUS_ID);

\! echo 'Loading NCPT DESCRIPTION Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NCPTRelease_PRODUCTION_20240412T120000Z/Full/Terminology/sct2_Description_NCPTFull-en_INT_20240101.txt'
 INTO TABLE DESCRIPTION
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (DESCRIPTION_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, CONCEPT_ID, LANGUAGE_CODE, TYPE_ID, TERM, CASE_SIGNIFICANCE_ID);

\! echo 'Loading NCPT INFERRED_RELATIONSHIP Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NCPTRelease_PRODUCTION_20240412T120000Z/Full/Terminology/sct2_Relationship_NCPTFull_INT_20240101.txt'
 INTO TABLE INFERRED_RELATIONSHIP
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);

\! echo 'Loading NCPT INFERRED_RELATIONSHIP_SNAP Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NCPTRelease_PRODUCTION_20240412T120000Z/Snapshot/Terminology/sct2_Relationship_NCPTSnapshot_INT_20240101.txt'
 INTO TABLE INFERRED_RELATIONSHIP_SNAP
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NCPTRelease_PRODUCTION_20240412T120000Z/Full/Terminology/sct2_sRefset_OWLExpressionNCPTFull_INT_20240101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NCPTRelease_PRODUCTION_20240412T120000Z/Full/Refset/Metadata/der2_cciRefset_NCPTRefsetDescriptorFull_INT_20240101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NCPTRelease_PRODUCTION_20240412T120000Z/Full/Refset/Metadata/der2_ssRefset_NCPTModuleDependencyFull_INT_20240101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NCPTRelease_PRODUCTION_20240412T120000Z/Full/Refset/Content/der2_Refset_NCPTSimpleFull_INT_20240101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);
