# Concept
LOAD DATA LOCAL INFILE "~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Full/Terminology/sct2_Concept_LOINCFull_INT_20170731.txt" INTO TABLE term.CONCEPT  FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (CONCEPT_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, DEFINITION_STATUS_ID);

# Description
LOAD DATA LOCAL INFILE "~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Full/Terminology/sct2_Description_LOINCFull-en_INT_20170731.txt" INTO TABLE term.DESCRIPTION FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (DESCRIPTION_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, CONCEPT_ID, LANGUAGE_CODE, TYPE_ID, TERM, CASE_SIGNIFICANCE_ID);

# Inferred Relationship
LOAD DATA LOCAL INFILE "~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Full/Terminology/sct2_Relationship_LOINCFull_INT_20170731.txt" INTO TABLE term.INFERRED_RELATIONSHIP FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);

# Inferred Relationship SNAPSHOT
LOAD DATA LOCAL INFILE '~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Snapshot/Terminology/sct2_Relationship_LOINCSnapshot_INT_20170731.txt'
 INTO TABLE INFERRED_RELATIONSHIP_SNAP
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);


# Stated Relationship
LOAD DATA LOCAL INFILE "~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Full/Terminology/sct2_StatedRelationship_LOINCFull_INT_20170731.txt" INTO TABLE term.STATED_RELATIONSHIP FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);

# Map Correlation Origin
LOAD DATA LOCAL INFILE "~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Full/Refset/Content/der2_scccRefset_LOINCMapCorrelationOriginFull_INT_20170731.txt" INTO TABLE term.REFERENCESET FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3, FIELD4);

# Exrpession Association
LOAD DATA LOCAL INFILE "~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Full/Refset/Content/der2_sscccRefset_LOINCExpressionAssociationFull_INT_20170731.txt" INTO TABLE term.REFERENCESET FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5);

# Language
LOAD DATA LOCAL INFILE "~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Full/Refset/Language/der2_cRefset_LOINCLanguageFull-en_INT_20170731.txt" INTO TABLE term.REFERENCESET FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

# Descriptor
LOAD DATA LOCAL INFILE "~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Full/Refset/Metadata/der2_cciRefset_LOINCRefsetDescriptorFull_INT_20170731.txt" INTO TABLE term.REFERENCESET FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

# Module Dependency
LOAD DATA LOCAL INFILE "~/resources/release_files/SnomedCT_LOINCRF2_PRODUCTION_20170831T120000Z/Full/Refset/Metadata/der2_ssRefset_LOINCModuleDependencyFull_INT_20170731.txt" INTO TABLE term.REFERENCESET FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);


