DROP  TABLE IF EXISTS MRCM_CONSTRAINTS;
CREATE TABLE MRCM_CONSTRAINTS (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  ATTRIBUTE_ID varchar(18) DEFAULT NULL,
  ATTRIBUTE_NAME varchar(255) DEFAULT NULL,
  SOURCE_ID varchar(18) DEFAULT NULL,
  SOURCE_NAME varchar(255) DEFAULT NULL,
  VALUE_ID varchar(18) DEFAULT NULL,
  VALUE_NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY IDX_MRCM_S_ID (SOURCE_ID),
  KEY IDX_MRCM_A_ID (ATTRIBUTE_ID),
  KEY IDX_MRCM_V_ID (VALUE_ID),
  KEY IDX_MRCM_S_ID_A_ID (SOURCE_ID, ATTRIBUTE_ID),
  KEY IDX_MRCM_A_ID_V_ID (ATTRIBUTE_ID, VALUE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

