--
-- SNOMED CT MySql load script.
--
-- http://dev.mysql.com/doc/refman/5.6/en/load-data.html
--
USE term;

\! echo 'Insert SCHEME';
 INSERT INTO term.SCHEME (ID, NAME, EDITION, VERSION, AUTHORITY, DATE) VALUES ('SNOMEDCT-v20260601', 'SNOMEDCT-Int', 'SNOMEDCT v20260601', 'v20260601', 'SNOMED International', '20260601');

\! echo 'Loading CONCEPT Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Terminology/sct2_Concept_Full_INT_20260601.txt' 
 INTO TABLE CONCEPT 
 FIELDS TERMINATED BY '\t' 
 LINES TERMINATED BY '\r\n' 
 IGNORE 1 LINES 

 (CONCEPT_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, DEFINITION_STATUS_ID);

\! echo 'Loading DESCRIPTION Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Terminology/sct2_Description_Full-en_INT_20260601.txt'
 INTO TABLE DESCRIPTION 
 FIELDS TERMINATED BY '\t' 
 LINES TERMINATED BY '\r\n' 
 IGNORE 1 LINES 

 (DESCRIPTION_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, CONCEPT_ID, LANGUAGE_CODE, TYPE_ID, TERM, CASE_SIGNIFICANCE_ID);

\! echo 'Loading INFERRED_RELATIONSHIP Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Terminology/sct2_Relationship_Full_INT_20260601.txt'
 INTO TABLE INFERRED_RELATIONSHIP 
 FIELDS TERMINATED BY '\t' 
 LINES TERMINATED BY '\r\n' 
 IGNORE 1 LINES 

 (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);

\! echo 'Loading INFERRED_RELATIONSHIP_SNAP Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Snapshot/Terminology/sct2_Relationship_Snapshot_INT_20260601.txt'
 INTO TABLE INFERRED_RELATIONSHIP_SNAP
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);

\! echo 'Loading INFERRED_RELATIONSHIP Concrete Values Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Terminology/sct2_RelationshipConcreteValues_Full_INT_20260601.txt'
 INTO TABLE INFERRED_RELATIONSHIP
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);

\! echo 'Loading INFERRED_RELATIONSHIP_SNAP Concrete Values Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Snapshot/Terminology/sct2_RelationshipConcreteValues_Snapshot_INT_20260601.txt'
 INTO TABLE INFERRED_RELATIONSHIP_SNAP
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);

\! echo 'Loading STATED_RELATIONSHIP Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Terminology/sct2_StatedRelationship_Full_INT_20260601.txt'
 INTO TABLE STATED_RELATIONSHIP 
 FIELDS TERMINATED BY '\t' 
 LINES TERMINATED BY '\r\n' 
 IGNORE 1 LINES 

 (RELATIONSHIP_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, SOURCE_ID, DESTINATION_ID, RELATIONSHIP_GROUP, TYPE_ID, CHARACTERISTIC_TYPE_ID, MODIFIER_ID);

\! echo 'Loading REFERENCESET Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Content/der2_cRefset_AssociationFull_INT_20260601.txt'
 INTO TABLE REFERENCESET 
 FIELDS TERMINATED BY '\t' 
 LINES TERMINATED BY '\r\n' 
 IGNORE 1 LINES 

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Content/der2_cRefset_AttributeValueFull_INT_20260601.txt'
 INTO TABLE REFERENCESET 
 FIELDS TERMINATED BY '\t' 
 LINES TERMINATED BY '\r\n' 
 IGNORE 1 LINES 

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Content/der2_Refset_SimpleFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Language/der2_cRefset_LanguageFull-en_INT_20260601.txt'
 INTO TABLE REFERENCESET 
 FIELDS TERMINATED BY '\t' 
 LINES TERMINATED BY '\r\n' 
 IGNORE 1 LINES 

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1); 

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Map/der2_iisssccRefset_ExtendedMapFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7);

 LOAD DATA LOCAL INFILE '~/resources/release_files/der2_iissscRefset_ComplexMapFull_INT_20160501.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

(REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Map/der2_sRefset_SimpleMapFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Metadata/der2_cciRefset_RefsetDescriptorFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Metadata/der2_ciRefset_DescriptionTypeFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Metadata/der2_cissccRefset_MRCMAttributeDomainFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Metadata/der2_cRefset_MRCMModuleScopeFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Metadata/der2_ssccRefset_MRCMAttributeRangeFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3, FIELD4);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Metadata/der2_ssRefset_ModuleDependencyFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Refset/Metadata/der2_sssssssRefset_MRCMDomainFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_InternationalRF2_PRODUCTION_20260601T120000Z/Full/Terminology/sct2_sRefset_OWLExpressionFull_INT_20260601.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

\! echo 'Loading MRCM_CONSTRAINTS Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/importer/snomedct/MySQL/MRCM/MRCM_CONSTRAINTS.txt'
 INTO TABLE MRCM_CONSTRAINTS
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'

 (ATTRIBUTE_ID, ATTRIBUTE_NAME, SOURCE_ID, SOURCE_NAME, VALUE_ID, VALUE_NAME);

\! echo 'Loading GP/FP Refset Table ';
-- 배포일이 다르므로 배포일 주의 !
-- 450970008, GPFP
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GPFP_PRODUCTION_20260331T120000Z/Full/Refset/Metadata/der2_cciRefset_GPFPRefsetDescriptorFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

(REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GPFP_PRODUCTION_20260331T120000Z/Full/Refset/Metadata/der2_ssRefset_GPFPModuleDependencyFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

(REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GPFP_PRODUCTION_20260331T120000Z/Full/Refset/Content/der2_Refset_GPFPSimpleFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

(REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);

-- GPFP와 같은 배포본. 450993002, SNOMED CT to ICPC-2 complex map, mapping FIELD6, FIELD7
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GPFP_PRODUCTION_20260331T120000Z/Full/Refset/Map/der2_iisssccRefset_GPFPExtendedMapFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

(REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7);

\! echo 'Loading INCP Refset Table ';

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_ICNPNursingPractice_PRODUCTION_20260331T120000Z/Full/Refset/Metadata/der2_cciRefset_ICNPRefsetDescriptorFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_ICNPNursingPractice_PRODUCTION_20260331T120000Z/Full/Refset/Metadata/der2_ssRefset_ICNPModuleDependencyFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_ICNPNursingPractice_PRODUCTION_20260331T120000Z/Full/Refset/Content/der2_Refset_ICNPSimpleFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);

\! echo 'Loading Nursing Activities Refset Table ';
-- 733990004, Nursing Activities Reference Set 
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NursingActivities_PRODUCTION_20211031T120000Z/Full/Refset/Metadata/der2_cciRefset_NursingActivitiesRefsetDescriptorFull_INT_20210731.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NursingActivities_PRODUCTION_20211031T120000Z/Full/Refset/Metadata/der2_ssRefset_NursingActivitiesModuleDependencyFull_INT_20210731.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NursingActivities_PRODUCTION_20211031T120000Z/Full/Refset/Content/der2_Refset_NursingActivitiesSimpleFull_INT_20210731.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);

\! echo 'Loading Nursing HealthIssues  Refset Table ';
-- 733991000, Nursing Health Issues Reference Set
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NursingHealthIssues_PRODUCTION_20211031T120000Z/Full/Refset/Metadata/der2_cciRefset_NursingHealthIssuesRefsetDescriptorFull_INT_20210731.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NursingHealthIssues_PRODUCTION_20211031T120000Z/Full/Refset/Metadata/der2_ssRefset_NursingHealthIssuesModuleDependencyFull_INT_20210731.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_NursingHealthIssues_PRODUCTION_20211031T120000Z/Full/Refset/Content/der2_Refset_NursingHealthIssuesSimpleFull_INT_20210731.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);

-- MedDRA
\! echo 'Loading SNOMEDCT-MedDRA Refset Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDMedDRAMapPackage_PRODUCTION_20260430T120000Z/Full/Refset/Metadata/der2_cciRefset_MedDRARefsetDescriptorFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDMedDRAMapPackage_PRODUCTION_20260430T120000Z/Full/Refset/Metadata/der2_ssRefset_MedDRAModuleDependencyFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

-- 816210007, SNOMED CT to MedDRA simple map reference set 
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDMedDRAMapPackage_PRODUCTION_20260430T120000Z/Full/Refset/Map/der2_sRefset_SNOMEDtoMedDRASimpleMapFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

-- 1193497006, MedDRA to SNOMED CT simple map
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDMedDRAMapPackage_PRODUCTION_20260430T120000Z/Full/Refset/Map/der2_sRefset_MedDRAtoSNOMEDSimpleMapFull_INT_20260101.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

-- 784008009, SNOMED CT to Orphanet simple map
\! echo 'Loading SNOMEDCT-Orphanet Refset Table ';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDOrphanetMapPackage_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_cciRefset_OrphanetRefsetDescriptorFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDOrphanetMapPackage_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_ssRefset_OrphanetModuleDependencyFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDOrphanetMapPackage_PRODUCTION_20250930T120000Z/Full/Refset/Map/der2_sRefset_OrphanetSimpleMapFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1);

-- 787778008, GPS
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GPS_PRODUCTION_20251015T120000Z/Full/Refset/Metadata/der2_cciRefset_GPSRefsetDescriptorFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GPS_PRODUCTION_20251015T120000Z/Full/Refset/Metadata/der2_ssRefset_GPSModuleDependencyFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GPS_PRODUCTION_20251015T120000Z/Full/Refset/Content/der2_Refset_GPSSimpleFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);

-- 816080008, International Patient Summary
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_IPS_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_cciRefset_IPSRefsetDescriptorFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_IPS_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_ssRefset_IPSModuleDependencyFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_IPS_PRODUCTION_20250930T120000Z/Full/Refset/Content/der2_Refset_IPSSimpleFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);

-- 1237627005, EDQM Map Package
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDEDQMMapPackage_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_cciRefset_EDQMRefsetDescriptorFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDEDQMMapPackage_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_ssRefset_EDQMModuleDependencyFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_SNOMEDEDQMMapPackage_PRODUCTION_20250930T120000Z/Full/Refset/Map/der2_ssRefset_EDQMSimpleMapFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

-- 721144007, General dentistry diagnostic reference set

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GeneralDentistry_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_cciRefset_DentistryRefsetDescriptorFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GeneralDentistry_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_ssRefset_DentistryModuleDependencyFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_GeneralDentistry_PRODUCTION_20250930T120000Z/Full/Refset/Content/der2_Refset_DentistrySimpleFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);

-- 721145008, Odontogram reference set

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_Odontogram_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_cciRefset_OdontogramRefsetDescriptorFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2, FIELD3);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_Odontogram_PRODUCTION_20250930T120000Z/Full/Refset/Metadata/der2_ssRefset_OdontogramModuleDependencyFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID, FIELD1, FIELD2);

LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/SnomedCT_Odontogram_PRODUCTION_20250930T120000Z/Full/Refset/Content/der2_Refset_OdontogramSimpleFull_INT_20250701.txt'
 INTO TABLE REFERENCESET
 FIELDS TERMINATED BY '\t'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (REFERENCESET_ID, EFFECTIVE_TIME, ACTIVE, MODULE_ID, REFSET_ID, REFERENCED_COMPONENT_ID);

