-- PostgreSQL 버전: REFERENCESET_ACTIVE 적재 스크립트
-- MySQL 원본(refset_active_loader.sql)을 PostgreSQL 문법으로 변환
-- 실행 전 REFERENCESET 테이블이 채워져 있어야 합니다.

SET search_path TO term, public;

TRUNCATE TABLE referenceset_active;

\echo 'Loading Descriptor ... '

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE, FIELD3_ID, FIELD3_VALUE)
SELECT
	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, '', R2.FIELD2, '', '', R2.FIELD3
	FROM (
		SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
		FROM term.REFERENCESET
		WHERE REFSET_ID = '900000000000456007'
		AND EFFECTIVE_TIME <= '20260601'
		GROUP BY REFERENCESET_ID

	) AS R1
	INNER JOIN term.REFERENCESET AS R2
	ON R2.REFSET_ID = R1.REFSET_ID
	AND R2.REFERENCESET_ID = R1.REFERENCESET_ID
	AND R2.EFFECTIVE_TIME = R1.MAX_ETIME
	WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has no further additional FIELD ...'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '' 
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
                        REFSET_ID = '723264001'
			OR REFSET_ID = '450970008'
			OR REFSET_ID = '1157358007'
			OR REFSET_ID = '733990004'
			OR REFSET_ID = '733991000'
			OR REFSET_ID = '787778008'
                        OR REFSET_ID = '816080008'
			OR REFSET_ID = '1303957004'
			OR REFSET_ID = '721144007'
			OR REFSET_ID = '721145008'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 and need to translate to Description... 1'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
                        REFSET_ID = '446608001'
                        OR REFSET_ID = '723563008'
                        OR REFSET_ID = '734138000'
                        OR REFSET_ID = '734139008'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 ... 2'

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
	FROM (
		SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
		FROM term.REFERENCESET
		WHERE (
			REFSET_ID = '900000000000489007'
			OR REFSET_ID = '900000000000490003'
		)
		AND EFFECTIVE_TIME <= '20260601'
		GROUP BY REFERENCESET_ID

	) AS R1
	INNER JOIN term.REFERENCESET AS R2
	ON R2.REFSET_ID = R1.REFSET_ID
	AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
	AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
	WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 ... 3'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE  REFSET_ID = '900000000000497000'
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 ... 4'

\echo 'Loading Refset that has the FIELD1 ... 5'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
                        REFSET_ID = '900000000000509007'
			OR REFSET_ID = '900000000000508004'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 ... 6'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
			REFSET_ID = '900000000000523009'
                        OR REFSET_ID = '900000000000524003'
                        OR REFSET_ID = '900000000000525002'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 ... 7'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
                        REFSET_ID = '900000000000526001'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 ... 8'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
                        REFSET_ID = '900000000000527005'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 ... 9'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
                        REFSET_ID = '900000000000528000'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 ... 10'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
                        REFSET_ID = '900000000000530003'
                        OR REFSET_ID = '900000000000531004'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 ... 11'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
                        REFSET_ID = '816210007'
			OR REFSET_ID = '784008009'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 but no need to translate to Description ... 1'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', '', R2.FIELD1
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
			REFSET_ID = '1193497006'
                )
                AND EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD1 but no need to translate to Description ... 2'

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE)
SELECT
	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', '', R2.FIELD1
	FROM (
		SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
		FROM term.REFERENCESET
		WHERE (
			REFSET_ID = '733073007'
			OR REFSET_ID = '762103008'
		)
		AND EFFECTIVE_TIME <= '20260601'
		GROUP BY REFERENCESET_ID

	) AS R1
	INNER JOIN term.REFERENCESET AS R2
	ON R2.REFSET_ID = R1.REFSET_ID
	AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
	AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
	WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD2 but no need to translate to Description ... 1'

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE)
SELECT
	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, '', '', R2.FIELD2
	FROM (
		SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
		FROM term.REFERENCESET
		WHERE (
				REFSET_ID = '900000000000538005'
			)
			AND EFFECTIVE_TIME <= '20260601'
			GROUP BY REFERENCESET_ID

	) AS R1
	INNER JOIN term.REFERENCESET AS R2
	ON R2.REFSET_ID = R1.REFSET_ID
	AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
	AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
	WHERE R2.ACTIVE=1
;

\echo 'Loading Refset that has the FIELD2 but no need to translate to Description ... 2'

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE)
SELECT
	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', '', R2.FIELD1, '', R2.FIELD2
	FROM (
		SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
		FROM term.REFERENCESET
		WHERE (
			REFSET_ID = '900000000000534007'
			OR REFSET_ID = '1237627005'
			)
			AND EFFECTIVE_TIME <= '20260601'
			GROUP BY REFERENCESET_ID

	) AS R1
	INNER JOIN term.REFERENCESET AS R2
	ON R2.REFSET_ID = R1.REFSET_ID
	AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
	AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
	WHERE R2.ACTIVE=1
;

\echo 'Loading refset that has FIELD 1(x),2(x),3(o),4(o) ...'

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE, FIELD3_ID, FIELD3_VALUE, FIELD4_ID, FIELD4_VALUE)
SELECT
	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', '', R2.FIELD1, '', R2.FIELD2, R2.FIELD3, '', R2.FIELD4, ''
	FROM (
		SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
		FROM term.REFERENCESET
		WHERE (
            		REFSET_ID = '723562003'
		)
            	AND EFFECTIVE_TIME <= '20260601'
			GROUP BY REFERENCESET_ID

	) AS R1
	INNER JOIN term.REFERENCESET AS R2
	ON R2.REFSET_ID = R1.REFSET_ID
	AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
	AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
	WHERE R2.ACTIVE=1
;

\echo 'Loading refset that has FIELD 1(o-LP), 2(o),3(o),4(o) ...'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE, FIELD3_ID, FIELD3_VALUE, FIELD4_ID, FIELD4_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, '', R2.FIELD2, '', R2.FIELD3, '', R2.FIELD4, ''
        FROM (
                SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
                FROM term.REFERENCESET
                WHERE (
                        REFSET_ID = '705112009'
                )
                AND EFFECTIVE_TIME <= '20260601'
                        GROUP BY REFERENCESET_ID

        ) AS R1
        INNER JOIN term.REFERENCESET AS R2
        ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
        WHERE R2.ACTIVE=1
;

\echo 'Loading refset that has FIELD 1(o-LOINC Code),2(x-Parsable String),3(o),4(o),5(o) ...'

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE, FIELD3_ID, FIELD3_VALUE, FIELD4_ID, FIELD4_VALUE, FIELD5_ID, FIELD5_VALUE)
SELECT
	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, '', '', R2.FIELD2, R2.FIELD3, '', R2.FIELD4, '', R2.FIELD5, ''
	FROM (
		SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
		FROM term.REFERENCESET
		WHERE (
			 REFSET_ID = '705110001'
		)
            	AND EFFECTIVE_TIME <= '20260601'
			GROUP BY REFERENCESET_ID

	) AS R1
	INNER JOIN term.REFERENCESET AS R2
	ON R2.REFSET_ID = R1.REFSET_ID
	AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
	AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
	WHERE R2.ACTIVE=1
;

\echo 'Loading refset that has FIELD 1(x),2(x),3(x),4(x),5(x), 6(o) (ICD-9-CM) ...'

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE, FIELD3_ID, FIELD3_VALUE, FIELD4_ID, FIELD4_VALUE,FIELD5_ID, FIELD5_VALUE, FIELD6_ID, FIELD6_VALUE)
SELECT
    	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', '', R2.FIELD1, '', R2.FIELD2, '', R2.FIELD3, '', R2.FIELD4, '', R2.FIELD5, R2.FIELD6, ''
    	FROM (
        	SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
        	FROM term.REFERENCESET
        	WHERE REFSET_ID = '447563008'
            		AND EFFECTIVE_TIME <= '20260601'
            	GROUP BY REFERENCESET_ID

    	) AS R1
    	INNER JOIN term.REFERENCESET AS R2
    	ON R2.REFSET_ID = R1.REFSET_ID
    		AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
    		AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
    	WHERE R2.ACTIVE=1
;

\echo 'Loading refset that has FIELD 1(o),2(x),3(x),4(x),5(o),6(o) ...'

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE, FIELD3_ID, FIELD3_VALUE, FIELD4_ID, FIELD4_VALUE, FIELD5_ID, FIELD5_VALUE, FIELD6_ID, FIELD6_VALUE)
SELECT
	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', R2.FIELD1, '', '', R2.FIELD2, '', R2.FIELD3, '', R2.FIELD4, R2.FIELD5, '', R2.FIELD6, ''
FROM (
	SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
	FROM term.REFERENCESET
	WHERE
	(
		REFSET_ID = '723561005'
	)
        	AND EFFECTIVE_TIME <= '20260601'
	GROUP BY REFERENCESET_ID

) AS R1
INNER JOIN term.REFERENCESET AS R2
ON R2.REFSET_ID = R1.REFSET_ID
	AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
	AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
WHERE R2.ACTIVE=1
;

\echo 'Loading refset that has FIELD 1(x),2(x),3(x),4(x),5(o),6(o),7(o) ...'

INSERT INTO term.REFERENCESET_ACTIVE
        (VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE, FIELD3_ID, FIELD3_VALUE, FIELD4_ID, FIELD4_VALUE, FIELD5_ID, FIELD5_VALUE, FIELD6_ID, FIELD6_VALUE, FIELD7_ID, FIELD7_VALUE)
SELECT
        CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', '', R2.FIELD1, '', R2.FIELD2, '', R2.FIELD3, '', R2.FIELD4, R2.FIELD5, '', R2.FIELD6, '', R2.FIELD7, ''
FROM (
	SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
        FROM term.REFERENCESET
        WHERE
        (

                REFSET_ID = '447562003'
                OR REFSET_ID = '450993002'
        )
               	AND EFFECTIVE_TIME <= '20260601'
       	GROUP BY REFERENCESET_ID

) AS R1
INNER JOIN term.REFERENCESET AS R2
ON R2.REFSET_ID = R1.REFSET_ID
        AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
        AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
WHERE R2.ACTIVE=1
;

\echo 'Loading refset that has FIELD 1(x),2(x),3(x),4(x),5(x),6(x),7(x) ...'

INSERT INTO term.REFERENCESET_ACTIVE
	(VERSION, UUID, EFFECTIVE_TIME, MODULE_ID, MODULE_NAME, REFSET_ID, REFSET_NAME, REFERENCED_COMPONENT_ID, REFERENCED_COMPONENT_ACTIVE, REFERENCED_COMPONENT_NAME, FIELD1_ID, FIELD1_VALUE, FIELD2_ID, FIELD2_VALUE, FIELD3_ID, FIELD3_VALUE, FIELD4_ID, FIELD4_VALUE, FIELD5_ID, FIELD5_VALUE, FIELD6_ID, FIELD6_VALUE, FIELD7_ID, FIELD7_VALUE)
SELECT
	CONCAT('INT-', '20260601'), R1.REFERENCESET_ID, R2.EFFECTIVE_TIME, R2.MODULE_ID, '', R2.REFSET_ID, '', R2.REFERENCED_COMPONENT_ID, R2.ACTIVE, '', '',R2.FIELD1, '', R2.FIELD2, '', R2.FIELD3, '', R2.FIELD4, '', R2.FIELD5, '', R2.FIELD6, '', R2.FIELD7
	FROM (
		SELECT REFSET_ID, REFERENCESET_ID, MAX(EFFECTIVE_TIME) AS MAX_ETIME
		FROM term.REFERENCESET
		WHERE
		(
            		REFSET_ID = '723560006'
            	)
            		AND EFFECTIVE_TIME <= '20260601'
		GROUP BY REFERENCESET_ID

	) AS R1
	INNER JOIN term.REFERENCESET AS R2
	ON R2.REFSET_ID = R1.REFSET_ID
		AND R1.REFERENCESET_ID = R2.REFERENCESET_ID
		AND R1.MAX_ETIME = R2.EFFECTIVE_TIME
WHERE R2.ACTIVE=1
;

\echo 'Loading DESCRIPTION for REFSET_ID...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT D1.CONCEPT_ID as D1CID, D1.TERM as D1T
	FROM (
		SELECT REFSET_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601'
		GROUP BY REFSET_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON D1.TYPE_ID = '900000000000003001'
    	AND D1.CONCEPT_ID = R1.REFSET_ID
	AND D1.ACTIVE = 1
) as R2
SET RA.REFSET_NAME = R2.D1T
WHERE RA.REFSET_ID = R2.D1CID;

\echo 'Loading DESCRIPTION for MODULE_NAME ...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT R1.MODULE_ID as R1MID, D1.TERM as D1T
	FROM (
		SELECT MODULE_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601'
		GROUP BY MODULE_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON D1.TYPE_ID = '900000000000003001'
    	AND D1.CONCEPT_ID = R1.MODULE_ID
	AND D1.ACTIVE = 1
) as R2
SET RA.MODULE_NAME = R2.D1T
WHERE RA.MODULE_ID = R2.R1MID;

\echo 'Loading DESCRIPTION for REFERENCED_COMPONENT_NAME : REFERENCE_COMPONENT_ID == CONCEPT_ID ...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT R1.REFERENCED_COMPONENT_ID as R1RCID, D1.TERM as D1T
	FROM (
		SELECT REFERENCED_COMPONENT_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601'
		GROUP BY REFERENCED_COMPONENT_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON D1.TYPE_ID = '900000000000003001'
    	  AND D1.CONCEPT_ID = R1.REFERENCED_COMPONENT_ID
	  AND D1.ACTIVE = 1
) as R2
SET RA.REFERENCED_COMPONENT_NAME = R2.D1T
WHERE RA.REFERENCED_COMPONENT_ID = R2.R1RCID;

\echo 'Loading DESCRIPTION for REFERENCED_COMPONENT_NAME : REFERENCE_COMPONENT_ID == DESCRIPTION_ID (US, GB) ...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
        SELECT R1.REFERENCED_COMPONENT_ID as R1RCID, D1.TERM as D1T
        FROM (
                SELECT REFERENCED_COMPONENT_ID, EFFECTIVE_TIME
                FROM term.REFERENCESET_ACTIVE
                WHERE EFFECTIVE_TIME <= '20260601'
                GROUP BY REFERENCED_COMPONENT_ID
        ) AS R1
        INNER JOIN term.DESCRIPTION AS D1
        ON D1.DESCRIPTION_ID = R1.REFERENCED_COMPONENT_ID 
          AND D1.ACTIVE = 1
) as R2
SET RA.REFERENCED_COMPONENT_NAME = R2.D1T
WHERE RA.REFERENCED_COMPONENT_ID = R2.R1RCID;

\echo 'Loading FSN of DESCRIPTION for FIELD1 VALUE(CONCEPT_ID)...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT R1.FIELD1_ID as R1F1ID, D1.TERM as D1T
	FROM (
		SELECT REFSET_ID, FIELD1_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601' AND FIELD1_ID is not null
		GROUP BY FIELD1_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON (
			R1.REFSET_ID = '705110001'
			OR R1.REFSET_ID = '705112009'
			OR R1.REFSET_ID = '723561005'
			OR R1.REFSET_ID = '723563008'
			OR R1.REFSET_ID = '734138000'
			OR R1.REFSET_ID = '734139008'
			OR R1.REFSET_ID = '900000000000456007'
			OR R1.REFSET_ID = '900000000000489007'
			OR R1.REFSET_ID = '900000000000490003'
			OR R1.REFSET_ID = '900000000000508004'
			OR R1.REFSET_ID = '900000000000509007'
			OR R1.REFSET_ID = '900000000000523009'
			OR R1.REFSET_ID = '900000000000524003'
			OR R1.REFSET_ID = '900000000000525002'
			OR R1.REFSET_ID = '900000000000526001'
			OR R1.REFSET_ID = '900000000000527005'
			OR R1.REFSET_ID = '900000000000528000'
			OR R1.REFSET_ID = '900000000000530003'
			OR R1.REFSET_ID = '900000000000531004'
			OR R1.REFSET_ID = '900000000000538005'
			OR R1.REFSET_ID = '450993002'
			OR R1.REFSET_ID = '816210007'
			OR R1.REFSET_ID = '784008009'
		)
		AND D1.TYPE_ID = '900000000000003001'
		AND D1.CONCEPT_ID = R1.FIELD1_ID
		AND D1.ACTIVE = 1
) as R2
SET RA.FIELD1_VALUE = R2.D1T
WHERE RA.FIELD1_ID = R2.R1F1ID;

\echo 'Loading DESCRIPTION for FIELD2 VALUE...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT R1.FIELD2_ID as R1F2ID, D1.TERM as D1T
	FROM (
		SELECT REFSET_ID, FIELD2_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601' AND FIELD2_ID is not null
		GROUP BY FIELD2_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON (
		R1.REFSET_ID = '705112009'
		OR R1.REFSET_ID = '900000000000456007'
	)
	AND D1.TYPE_ID = '900000000000003001'
    	AND D1.CONCEPT_ID = R1.FIELD2_ID
	AND D1.ACTIVE = 1
) as R2
SET RA.FIELD2_VALUE = R2.D1T
WHERE RA.FIELD2_ID = R2.R1F2ID;

\echo 'Loading DESCRIPTION for FIELD3 VALUE...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT R1.FIELD3_ID as R1F3ID, D1.TERM as D1T
	FROM (
		SELECT REFSET_ID, FIELD3_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601' AND FIELD3_ID is not null
		GROUP BY FIELD3_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON (	
		R1.REFSET_ID = '705110001'
		OR R1.REFSET_ID = '705112009'
		OR R1.REFSET_ID = '723562003'
	)
	AND D1.TYPE_ID = '900000000000003001'
    AND D1.CONCEPT_ID = R1.FIELD3_ID
	AND D1.ACTIVE = 1
) as R2
SET RA.FIELD3_VALUE = R2.D1T
WHERE RA.FIELD3_ID = R2.R1F3ID;

\echo 'Loading DESCRIPTION for FIELD4 VALUE...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT R1.FIELD4_ID as R1F4ID, D1.TERM as D1T
	FROM (
		SELECT REFSET_ID, FIELD4_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601' AND FIELD4_ID is not null
		GROUP BY FIELD4_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON (
		R1.REFSET_ID = '705110001'
		OR R1.REFSET_ID = '705112009'
		OR R1.REFSET_ID = '723562003'
	)
	AND D1.TYPE_ID = '900000000000003001'
    AND D1.CONCEPT_ID = R1.FIELD4_ID
	AND D1.ACTIVE = 1
) as R2
SET RA.FIELD4_VALUE = R2.D1T
WHERE RA.FIELD4_ID = R2.R1F4ID;

\echo 'Loading DESCRIPTION for FIELD5 VALUE...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT R1.FIELD5_ID as R1F5ID, D1.TERM as D1T
	FROM (
		SELECT REFSET_ID, FIELD5_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601' AND FIELD5_ID is not null
		GROUP BY FIELD5_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON
	(
		R1.REFSET_ID = '705110001'
		OR R1.REFSET_ID = '723561005'
	)
	AND D1.TYPE_ID = '900000000000003001'
    	AND D1.CONCEPT_ID = R1.FIELD5_ID
	AND D1.ACTIVE = 1
) as R2
SET RA.FIELD5_VALUE = R2.D1T
WHERE RA.FIELD5_ID = R2.R1F5ID;

\echo 'Loading DESCRIPTION for FIELD6 VALUE...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT R1.FIELD6_ID as R1F6ID, D1.TERM as D1T
	FROM (
		SELECT REFSET_ID, FIELD6_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601' AND FIELD6_ID is not null
		GROUP BY FIELD6_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON (
                R1.REFSET_ID = '723561005'
		OR R1.REFSET_ID = '447563008'
		OR R1.REFSET_ID = '447562003'
		OR R1.REFSET_ID = '450993002'
	)
	AND D1.TYPE_ID = '900000000000003001'
    	AND D1.CONCEPT_ID = R1.FIELD6_ID
	AND D1.ACTIVE = 1
) as R2
SET RA.FIELD6_VALUE = R2.D1T
WHERE RA.FIELD6_ID = R2.R1F6ID;

\echo 'Loading DESCRIPTION for FIELD7 VALUE...'

UPDATE term.REFERENCESET_ACTIVE as RA,
(
	SELECT R1.FIELD7_ID as R1F7ID, D1.TERM as D1T
	FROM (
		SELECT REFSET_ID, FIELD7_ID, EFFECTIVE_TIME
		FROM term.REFERENCESET_ACTIVE
		WHERE EFFECTIVE_TIME <= '20260601' AND FIELD7_ID is not null
		GROUP BY FIELD7_ID
	) AS R1
	INNER JOIN term.DESCRIPTION AS D1
	ON (
		R1.REFSET_ID = '447562003'
		OR R1.REFSET_ID = '450993002'
	)
	AND D1.TYPE_ID = '900000000000003001'
    AND D1.CONCEPT_ID = R1.FIELD7_ID
	AND D1.ACTIVE = 1
) as R2
SET RA.FIELD7_VALUE = R2.D1T
WHERE RA.FIELD7_ID = R2.R1F7ID;
