use term;


DROP  TABLE IF EXISTS REFERENCESET_ACTIVE;
CREATE TABLE REFERENCESET_ACTIVE (
  VERSION char(12) NOT NULL,
  UUID char(36) NOT NULL,
  EFFECTIVE_TIME char(8) NOT NULL,
  MODULE_ID varchar(18) NOT NULL,
  MODULE_NAME varchar(255) NOT NULL,
  REFSET_ID varchar(18) NOT NULL,
  REFSET_NAME varchar(255) NOT NULL,
  REFERENCED_COMPONENT_ID varchar(18) NOT NULL,
  REFERENCED_COMPONENT_ACTIVE tinyint(1) NOT NULL,
  REFERENCED_COMPONENT_NAME varchar(255) NOT NULL,
  FIELD1_ID varchar(18) DEFAULT NULL,
  FIELD1_VALUE varchar(2047) DEFAULT NULL,
  FIELD2_ID varchar(18) DEFAULT NULL,
  FIELD2_VALUE varchar(550) DEFAULT NULL,
  FIELD3_ID varchar(18) DEFAULT NULL,
  FIELD3_VALUE varchar(255) DEFAULT NULL,
  FIELD4_ID varchar(18) DEFAULT NULL,
  FIELD4_VALUE varchar(399) DEFAULT NULL,
  FIELD5_ID varchar(18) DEFAULT NULL,
  FIELD5_VALUE varchar(6200) DEFAULT NULL,
  FIELD6_ID varchar(18) DEFAULT NULL,
  FIELD6_VALUE varchar(6200) DEFAULT NULL,
  FIELD7_ID varchar(18) DEFAULT NULL,
  FIELD7_VALUE varchar(35) DEFAULT NULL,
  DATE_CREATED char(8) DEFAULT NULL,
  PRIMARY KEY (VERSION, UUID),
  KEY IDX_REFSET_ACTIVE_EU (EFFECTIVE_TIME, UUID) USING BTREE,
  KEY IDX_REFSET_ACITVE_URCID (UUID, REFERENCED_COMPONENT_ID) USING BTREE,
  KEY IDX_REFSET_ACTIVE_URCUDE (UUID, REFERENCED_COMPONENT_ID, EFFECTIVE_TIME) USING BTREE,
  KEY IDX_REFSET_ACITVE_URCIDF1AE (UUID, REFERENCED_COMPONENT_ID, FIELD1_ID, REFERENCED_COMPONENT_ACTIVE, EFFECTIVE_TIME) USING BTREE,
  KEY IDX_REFSET_REFSET (REFSET_ID) USING BTREE,
  KEY IDX_REFSET_F1 (FIELD1_ID) USING BTREE,
  KEY IDX_REFSET_F2 (FIELD2_ID) USING BTREE,
  KEY IDX_REFSET_F3 (FIELD3_ID) USING BTREE,
  KEY IDX_REFSET_F4 (FIELD4_ID) USING BTREE,
  KEY IDX_REFSET_F5 (FIELD5_ID) USING BTREE,
  KEY IDX_REFSET_F6 (FIELD6_ID) USING BTREE,
  KEY IDX_REFSET_F7 (FIELD7_ID) USING BTREE,
  FULLTEXT KEY INEX_REFSET_RCNAME (REFERENCED_COMPONENT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


