--
-- LOINC MySql load script.
--
-- http://dev.mysql.com/doc/refman/5.6/en/load-data.html
--

USE loinc;

\! echo 'Loading LOINC Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/LoincTable/Loinc.csv' 
 INTO TABLE LOINC 
 FIELDS TERMINATED BY ',' 
 OPTIONALLY ENCLOSED BY '"' 
 LINES TERMINATED BY '\r\n'  
 IGNORE 1 LINES
 
 (
  CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM,SCALE_TYPE,METHOD_TYPE, 
  CLASS_NAME,
  LAST_CHANGED_VERSION,
  CHANGE_TYPE, 
  DEFINITION_DESCRIPTION, 
  STATUS, 
  CONSUMER_NAME, 
  CLASS_TYPE, 
  FORMULA, 
  EXAMPLE_ANSWERS,
  SURVEY_QUEST_TEXT,
  SURVEY_QUEST_SRC,
  UNITS_REQUIRED,
  SUBMITTED_UNITS,
  RELATED_NAMES2, 
  SHORT_NAME,
  ORDER_OBS,
  CDISC_COMMON_TESTS,
  HL7_FIELD_SUBFIELD_ID,
  EXTERNAL_COPYRIGHT_NOTICE,
  EXAMPLE_UNITS, 
  LONG_COMMON_NAME,
  UNITS_AND_RANGE,
  EXAMPLE_UCUM_UNITS,
  EXAMPLE_SI_UCUM_UNITS,
  STATUS_REASON,
  STATUS_TEXT,
  CHANGE_REASON_PUBLIC,
  COMMON_TEST_RANK,
  COMMON_ORDER_RANK,
  COMMON_SI_TEST_RANK,
  HL7_ATTACHMENT_STRUCTURE,
  EXTERNAL_COPYRIGHT_LINK,
  PANEL_TYPE,
  ASK_AT_ORDER_ENTRY,
  ASSOCIATED_OBSERVATIONS,
  FIRST_RELEASED_VERSION,
  VALID_HL7_ATTACHMENT_REQUEST,
  DISPLAY_NAME
 );

\! echo 'Loading MAP_TO Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/LoincTable/MapTo.csv' 
 INTO TABLE MAP_TO 
 FIELDS TERMINATED BY ',' 
 OPTIONALLY ENCLOSED BY '"' 
 LINES TERMINATED BY '\r\n'  
 IGNORE 1 LINES

 ( CODE, MAP_TO, COMMENT );

\! echo 'Loading SOURCE_ORGANIZATION Table';
 LOAD  DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/LoincTable/SourceOrganization.csv' 
 INTO TABLE SOURCE_ORGANIZATION
 FIELDS TERMINATED BY ',' 
 OPTIONALLY ENCLOSED BY '"' 
 LINES TERMINATED BY '\r\n'  
 IGNORE 1 LINES

 ( ID, COPYRIGHT_ID, NAME, COPYRIGHT, TERMS_OF_USE, URL );

# HIERARCHY
# LOAD  DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/MultiAxialHierarchy/MultiAxialHierarchy.csv'
# INTO TABLE HIERARCHY
# FIELDS TERMINATED BY ','
# OPTIONALLY ENCLOSED BY '"'
# LINES TERMINATED BY '\r\n'
# IGNORE 1 LINES

# ( PATH, SEQUENCE, PARENT, CODE, NAME );

\! echo 'Loading HIERARCHY_TMP Table';
# HIERARCHY TMP
 LOAD  DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/ComponentHierarchyBySystem/ComponentHierarchyBySystem.csv'
 INTO TABLE HIERARCHY_TMP
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( PATH, SEQUENCE, PARENT, CODE, NAME );

#### PROPERTY Table

#LOAD DATA LOCAL INFILE '../loinc_property.csv'
#INTO TABLE LOINC.PROPERTY
#FIELDS TERMINATED BY ','
#OPTIONALLY ENCLOSED BY '"'
#LINES TERMINATED BY '\r\n'
#IGNORE 1 LINES
#(
#  CATEGORY,
#  VALUE,
#  DESCRIPTION  -- 만약 *로 시작한다면, IUPAC Silver Book^xx로 부터 온 값
#);

#### CLASS Table
\! echo 'Loading CLASS Table';
LOAD DATA LOCAL INFILE '../Extension/loinc_2.73_class.csv'
INTO TABLE CLASS
FIELDS TERMINATED BY '\t'
####OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( TYPE, NAME, ABBREVIATION, TERM );

UPDATE CLASS
SET NAME = REPLACE(NAME, ' ', '_');

#### LinguaiticVariants Table
\! echo 'Loading LINGUISTIC_VARIANTS Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/LinguisticVariants.csv'
INTO TABLE LINGUISTIC_VARIANTS
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( ID, ISO_LANG, ISO_COUNTRY, LANG, PRODUCER );

#### LinguisticVariant Table (arJO32)
\! echo 'Loading LINGUISTIC_VARIANT(arJO32) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/arJO32LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'JO', ISO_LANG = 'ar';

#### LinguisticVariant Table (csCZ33)
\! echo 'Loading LINGUISTIC_VARIANT(csCZ33) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/csCZ33LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'CZ', ISO_LANG = 'cs';

#### LinguisticVariant Table (deAT24)
\! echo 'Loading LINGUISTIC_VARIANT(deAT24) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/deAT24LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'AT', ISO_LANG = 'de';

#### LinguisticVariant Table (deDE15)
\! echo 'Loading LINGUISTIC_VARIANT(deDE15) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/deDE15LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'DE', ISO_LANG = 'de';

#### LinguisticVariant Table (elGR17)
\! echo 'Loading LINGUISTIC_VARIANT(elGR17) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/elGR17LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'GR', ISO_LANG = 'el';

#### LinguisticVariant Table (esAR7)
\! echo 'Loading LINGUISTIC_VARIANT(esAR7) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/esAR7LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'AR', ISO_LANG = 'es';

#### LinguisticVariant Table (esES12)
\! echo 'Loading LINGUISTIC_VARIANT(esES12) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/esES12LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'ES', ISO_LANG = 'es';

#### LinguisticVariant Table (esMX28)
\! echo 'Loading LINGUISTIC_VARIANT(esMX28) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/esMX28LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'MX', ISO_LANG = 'es';

#### LinguisticVariant Table (etEE10)
\! echo 'Loading LINGUISTIC_VARIANT(etEE10) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/etEE10LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'EE', ISO_LANG = 'et';

#### LinguisticVariant Table (frBE23)
\! echo 'Loading LINGUISTIC_VARIANT(frBE23) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/frBE23LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'BE', ISO_LANG = 'fr';

#### LinguisticVariant Table (frCA8)
\! echo 'Loading LINGUISTIC_VARIANT(frCA8) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/frCA8LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'CA', ISO_LANG = 'fr';

#### LinguisticVariant Table (frFR18)
\! echo 'Loading LINGUISTIC_VARIANT(frFR18) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/frFR18LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'FR', ISO_LANG = 'fr';

#### LinguisticVariant Table (itIT16)
\! echo 'Loading LINGUISTIC_VARIANT(itIT16) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/itIT16LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'IT', ISO_LANG = 'it';

#### LinguisticVariant Table (koKR13)
\! echo 'Loading LINGUISTIC_VARIANT(koKR13) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/koKR13LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'KR', ISO_LANG = 'ko';

#### LinguisticVariant Table (nlNL22)
\! echo 'Loading LINGUISTIC_VARIANT(nlNL22) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/nlNL22LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'NL', ISO_LANG = 'nl';

#### LinguisticVariant Table (plPL29)
\! echo 'Loading LINGUISTIC_VARIANT(plPL29) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/plPL29LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'PL', ISO_LANG = 'pl';

#### LinguisticVariant Table (ptBR11)
\! echo 'Loading LINGUISTIC_VARIANT(ptBR11) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/ptBR11LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'BR', ISO_LANG = 'pt';

#### LinguisticVariant Table (ruRU20)
\! echo 'Loading LINGUISTIC_VARIANT(ruRU20) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/ruRU20LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'RU', ISO_LANG = 'ru';

#### LinguisticVariant Table (trTR19)
\! echo 'Loading LINGUISTIC_VARIANT(trTR19) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/trTR19LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'TR', ISO_LANG = 'tr';

#### LinguisticVariant Table (ukUA30)
\! echo 'Loading LINGUISTIC_VARIANT(ukUA30) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/ukUA30LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'UA', ISO_LANG = 'uk';

#### LinguisticVariant Table (zhCN5)
\! echo 'Loading LINGUISTIC_VARIANT(zhCN5) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/zhCN5LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'CN', ISO_LANG = 'zh';

#### LinguisticVariant Table (deCH)
#\! echo 'Loading LINGUISTIC_VARIANT(deCH) Table';
#LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/deCH1LinguisticVariant.csv'
#INTO TABLE LINGUISTIC_VARIANT
#FIELDS TERMINATED BY ','
#OPTIONALLY ENCLOSED BY '"'
#LINES TERMINATED BY '\r\n'
#IGNORE 1 LINES

#( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

#SET ISO_COUNTRY = 'CH', ISO_LANG = 'de';

#### LinguisticVariant Table (frCH)
#\! echo 'Loading LINGUISTIC_VARIANT(frCH) Table';
#LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LinguisticVariants.69/AccessoryFiles/LinguisticVariants/frCH2LinguisticVariant.csv'
#INTO TABLE LINGUISTIC_VARIANT
#FIELDS TERMINATED BY ','
#OPTIONALLY ENCLOSED BY '"'
#LINES TERMINATED BY '\r\n'
#IGNORE 1 LINES

#( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

#SET ISO_COUNTRY = 'CH', ISO_LANG = 'fr';

#### LinguisticVariant Table (itCH)
#\! echo 'Loading LINGUISTIC_VARIANT(itCH) Table';
#LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/itCH3LinguisticVariant.csv'
#INTO TABLE LINGUISTIC_VARIANT
#FIELDS TERMINATED BY ','
#OPTIONALLY ENCLOSED BY '"'
#LINES TERMINATED BY '\r\n'
#IGNORE 1 LINES

#( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

#SET ISO_COUNTRY = 'CH', ISO_LANG = 'it';

#### LinguisticVariant Table (esCH)
#\! echo 'Loading LINGUISTIC_VARIANT(esCH) Table';
#LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/LinguisticVariants/esCH4LinguisticVariant.csv'
#INTO TABLE LINGUISTIC_VARIANT
#FIELDS TERMINATED BY ','
#OPTIONALLY ENCLOSED BY '"'
#LINES TERMINATED BY '\r\n'
#IGNORE 1 LINES

#( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

#SET ISO_COUNTRY = 'CH', ISO_LANG = 'es';

#### LOINC PANEL
\! echo 'Loading PANEL Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/PanelsAndForms/PanelsAndForms.csv'
 INTO TABLE PANEL
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( PARENT_ID, PARENT_CODE, PARENT_NAME, ID, SEQUENCE, CODE, NAME, DISPLAY_NAME_FOR_FORM, OBSERVATION_REQUIRED_IN_PANEL, OBSERVATION_ID_IN_FORM, SKIP_LOGIC_HELP_TEXT, DEFAULT_VALUE, ENTRY_TYPE, DATA_TYPE_IN_FORM, DATA_TYPE_SOURCE, ANSWER_SEQUENCE_OVERRIDE, CONDITION_FOR_INCLUSION, ALLOWABLE_ALTERNATIVE, OBSERVATION_CATEGORY, CONTEXT, CONSISTENCY_CHECKS, RELEVANCE_EQUATION, CODING_INSTRUCTIONS, QUESTION_CARDINALITY, ANSWER_CARDINALITY, ANSWER_LIST_ID_OVERRIDE, ANSWER_LIST_TYPE_OVERRIDE, EXTERNAL_COPYRIGHT_NOTICE);

#### LOINC PART
\! echo 'Loading LP Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/PartFile/Part.csv'
 INTO TABLE LP
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( PART_NUMBER, PART_TYPE_NAME, PART_NAME, PART_DISPLAY_NAME, STATUS );

#### LOINC PART LINK

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/PartFile/LoincPartLink_Primary.csv'
 INTO TABLE LP_LINK
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( LOINC_NUMBER, LONG_COMMON_NAME, PART_NUMBER, PART_NAME, PART_CODE_SYSTEM, PART_TYPE_NAME, LINK_TYPE_NAME, PROPERTY );

#### LOINC PART LINK

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/PartFile/LoincPartLink_Supplementary.csv'
 INTO TABLE LP_LINK
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( LOINC_NUMBER, LONG_COMMON_NAME, PART_NUMBER, PART_NAME, PART_CODE_SYSTEM, PART_TYPE_NAME, LINK_TYPE_NAME, PROPERTY );


#### LOINC PART MAP

 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/PartFile/PartRelatedCodeMapping.csv'
 INTO TABLE LP_MAP
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( PART_NUMBER, PART_NAME, PART_TYPE_NAME, EXT_CODE_ID, EXT_CODE_DISPLAY_NAME, EXT_CODE_SYSTEM, EQUIVALENCE, CONTENT_ORIGIN, EXT_CODE_SYSTEM_VERSION, EXT_CODE_SYSTEM_COPYRIGHT_NOTICE );

#### LOINC ANSWER
\! echo 'Loading LA Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/AnswerFile/AnswerList.csv'
 INTO TABLE LA
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( ANSWER_LIST_ID, ANSWER_LIST_NAME, ANSWER_LIST_OID, EXT_DEFINED_YN, EXT_DEFINED_ANSWER_LIST_CODE_SYSTEM, EXT_DEFINED_ANSWER_LIST_LINK, ANSWER_STRING_ID, LOCAL_ANSWER_CODE, LOCAL_ANSWER_CODE_SYSTEM, SEQUENCE_NUMBER, DISPLAY_TEXT, EXT_CODE_ID, EXT_CODE_DISPLAY_NAME, EXT_CODE_SYSTEM, EXT_CODE_SYSTEM_VERSION, EXT_CODE_SYSTEM_COPYRIGHT_NOTICE, SUBSEQUENCE_TEXT_PROMPT, DESCRIPTION, SCORE ); 

#### LOINC ANSWER LINK
\! echo 'Loading LA_LINK Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/AnswerFile/LoincAnswerListLink.csv'
 INTO TABLE LA_LINK
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( LOINC_NUMBER, LONG_COMMON_NAME, ANSWER_LIST_ID, ANSWER_LIST_NAME, ANSWER_LIST_LINK_TYPE, APPLICABLE_CONTEXT );

USE loinc;

#### LOINC GROUP
\! echo 'Loading PARENT_LG Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/GroupFile/ParentGroup.csv'
 INTO TABLE PARENT_LG
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( PARENT_LG_ID, PARENT_LG, STATUS );

#### LOINC GROUP
\! echo 'Loading PARENT_LG_ATTRIBUTES Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/GroupFile/ParentGroupAttributes.csv'
 INTO TABLE PARENT_LG_ATTRIBUTES
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( PARENT_LG_ID, TYPE, VALUE );

#### LOINC GROUP
\! echo 'Loading LG Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/GroupFile/Group.csv'
 INTO TABLE LG 
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( PARENT_LG_ID, LG_ID, LG, ARCHETYPE, STATUS, VERSION_FIRST_RELEASED );

#### LOINC GROUP ATTRIBUTES
\! echo 'Loading LG_ATTRIBUTES';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/GroupFile/GroupAttributes.csv'
 INTO TABLE LG_ATTRIBUTES
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( PARENT_LG_ID, LG_ID, TYPE, VALUE );

#### LOINC GROUP LOINC TERMS
\! echo 'Loading LG_TERMS';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.82/AccessoryFiles/GroupFile/GroupLoincTerms.csv'
 INTO TABLE LG_TERMS
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 ( CATEGORY, LG_ID, ARCHETYPE, LOINC_NUMBER, LONG_COMMON_NAME );

