USE loinc;

\! echo 'additional1';
#HIERARCHY
\! echo '- Initializing HIERARCHY Table...';
INSERT INTO HIERARCHY (CODE, PATH, PARENT, TYPE, SEQUENCE, NAME, PREFERRED_NAME)
VALUES
#("CLASS", "", "", 0, 1, "LOINCCLASSTYPES", "Class Types"),
#("PARTS", "", "", 0, 2, "LOINCPARTS","Parts"),
("LABORATORY", "CLASS", "CLASS", 1, 1, "Laboratory Class", "Laboratory Class"),
("CLINICAL", "CLASS", "CLASS", 1, 2, "Clinical Class", "Clinical Class"),
("CLAIMS_ATTACHMENT", "CLASS", "CLASS", 1, 3, "Claims Attachment", "Claims Attachment"),
("SURVEYS", "CLASS", "CLASS", 1, 4, "Surveys", "Surveys");

INSERT INTO HIERARCHY (CODE, PATH, PARENT, TYPE, SEQUENCE, NAME, PREFERRED_NAME)
SELECT ABBREVIATION, CONCAT("CLASS~", UPPER(NAME)), UPPER(NAME), 1, 0, TERM, TERM
FROM CLASS;

# LOINC의CODE를 HIERARCHY로 insert (PATH 생성, NAME은 Component 이름)
\! echo '- Inserting LOINC Code, Name and PATH...';
INSERT INTO HIERARCHY
        (CODE, PATH, PARENT, TYPE, SEQUENCE, NAME) 
        #SELECT l.CODE, CONCAT("CLASS~", UPPER(j0.NAME), "~", l.CLASS_NAME), l.CLASS_NAME, 1, 1, l.COMPONENT
	SELECT l.CODE, CONCAT("CLASS~", UPPER(j0.NAME), "~", j0.ABBREVIATION), j0.ABBREVIATION, 1, 1, l.SHORT_NAME
	FROM LOINC as l
		JOIN (
			SELECT c.NAME, c.ABBREVIATION
			FROM CLASS as c
		) j0
            	ON REPLACE(l.CLASS_NAME, '/', '-') = j0.ABBREVIATION; 

# Change space( ) to sharp(#) in PATH for PARENT
\! echo '- Changing space to sharp(#) for PARENT...';
UPDATE HIERARCHY
SET PARENT = REPLACE(PARENT, ' ', '#');

UPDATE HIERARCHY
SET PATH = REPLACE(PATH, ' ', '#');

# Preferred Name 생성...
\! echo '- Creating Preferred Name...';
UPDATE HIERARCHY INNER JOIN LOINC
ON HIERARCHY.CODE = LOINC.CODE
SET HIERARCHY.PREFERRED_NAME = CONCAT(LOINC.COMPONENT,":", LOINC.PROPERTY,":", LOINC.TIME_ASPECT,":", LOINC.SYSTEM,":", LOINC.SCALE_TYPE);

UPDATE HIERARCHY INNER JOIN LOINC
ON HIERARCHY.CODE = LOINC.CODE AND LOINC.METHOD_TYPE <> '' 
SET HIERARCHY.PREFERRED_NAME = CONCAT(LOINC.COMPONENT,":", LOINC.PROPERTY,":", LOINC.TIME_ASPECT,":", LOINC.SYSTEM,":", LOINC.SCALE_TYPE,":",LOINC.METHOD_TYPE);

# HIERARCHY_TMP

# HIERARCHY_TMP의 PATH내 .을 ~로 변경
\! echo '- Converting . to ~ in PATH...';
UPDATE HIERARCHY_TMP
SET PATH = REPLACE(PATH, '.', '~');

# HIERARCHY_TMP의 PATH (PARTS~ ... ), NAME(LOINC.COMPONENT) 변경

UPDATE HIERARCHY_TMP
SET PATH=CONCAT("PARTS~", PATH);

UPDATE HIERARCHY_TMP
SET PATH = "PARTS", PARENT = "PARTS", PREFERRED_NAME = NAME
WHERE PATH = "PARTS~";

## TYPE 값 채움
\! echo '- Filling out TYPE value...';
UPDATE HIERARCHY_TMP
SET TYPE = "2";

# for LOINC PARTS (LP)
\! echo '- Filling out PREFERRED_NAME for LP...';
UPDATE HIERARCHY_TMP
SET PREFERRED_NAME = NAME
WHERE PREFERRED_NAME is null;

# for LOINC code
\! echo '- Filling out CODE...';
UPDATE HIERARCHY_TMP INNER JOIN LOINC
ON HIERARCHY_TMP.CODE = LOINC.CODE
SET HIERARCHY_TMP.PREFERRED_NAME = CONCAT(LOINC.COMPONENT,":", LOINC.PROPERTY,":", LOINC.TIME_ASPECT,":", LOINC.SYSTEM,":", LOINC.SCALE_TYPE);

UPDATE HIERARCHY_TMP INNER JOIN LOINC
ON HIERARCHY_TMP.CODE = LOINC.CODE AND LOINC.METHOD_TYPE <> '' 
SET HIERARCHY_TMP.PREFERRED_NAME = CONCAT(LOINC.COMPONENT,":", LOINC.PROPERTY,":", LOINC.TIME_ASPECT,":", LOINC.SYSTEM,":", LOINC.SCALE_TYPE,":",LOINC.METHOD_TYPE);

# CHILDREN_COUNT
\! echo '- Counting HIERARCHY Children...';
update HIERARCHY as h,
(
SELECT PARENT, count(*) as cnt
FROM HIERARCHY AS h1
        JOIN (
                SELECT CODE as c
                FROM HIERARCHY as h2
                WHERE CODE REGEXP '^[A-Z]'
        ) AS g
        ON h1.PATH LIKE CONCAT("%",g.c)
WHERE h1.PARENT = g.c GROUP BY g.c
) as i
SET h.CHILDREN_COUNT = i.cnt
WHERE h.CODE =i.PARENT;

# CHILDREN_COUNT TMP
\! echo '- Counting HIERARCHY_TMP Children...';
update HIERARCHY_TMP as h,
(
SELECT PARENT, count(*) as cnt
FROM HIERARCHY_TMP AS h1
        JOIN (
                SELECT CODE as c
                FROM HIERARCHY_TMP as h2
                WHERE CODE REGEXP '^[A-Z]'
        ) AS g
        ON h1.PATH LIKE CONCAT("%",g.c)
WHERE h1.PARENT = g.c GROUP BY g.c
) as i
SET h.CHILDREN_COUNT = i.cnt
WHERE h.CODE =i.PARENT;

# DESCENDANT_COUNT
\! echo '- Counting HIERARCHY Descendant...';
update HIERARCHY as h,
(
SELECT TRIM(TRAILING '%' FROM SUBSTRING_INDEX(g.p,'~',-1)) as s, count(*) as cnt
FROM HIERARCHY AS h1
        INNER JOIN
    	(
        	SELECT CONCAT(PATH, '~', CODE, '%') AS p
        	FROM HIERARCHY as h2
        	WHERE CODE REGEXP '^[A-Z]'
        ) AS g
    	ON h1.PATH LIKE g.p
WHERE h1.PATH LIKE g.p GROUP BY g.p
) as i
SET h.DESCENDANT_COUNT = i.cnt
WHERE h.CODE = i.s
;

# DESCENDANT_COUNT TMP
\! echo '- Counting HIERARCHY_TMP Descendant...';
update HIERARCHY_TMP as h,
(
SELECT TRIM(TRAILING '%' FROM SUBSTRING_INDEX(g.p,'~',-1)) as s, count(*) as cnt
FROM HIERARCHY_TMP AS h1
        INNER JOIN
    	(	
                SELECT CONCAT(PATH, '~', CODE, '%') AS p
        	FROM HIERARCHY_TMP as h2
        	WHERE CODE REGEXP '^[A-Z]'
        ) AS g
    	ON h1.PATH LIKE g.p
WHERE h1.PATH LIKE g.p GROUP BY g.p
) as i
SET h.DESCENDANT_COUNT = i.cnt
WHERE h.CODE = i.s;

# add HIERARCHY_TMP to HIERARCHY
\! echo '- Transfer TMP to HIERARCHY...';
INSERT INTO HIERARCHY (CHILDREN_COUNT, CODE, DESCENDANT_COUNT, PATH, PARENT, TYPE, SEQUENCE, NAME, PREFERRED_NAME)
SELECT HIERARCHY_TMP.CHILDREN_COUNT, HIERARCHY_TMP.CODE, HIERARCHY_TMP.DESCENDANT_COUNT, HIERARCHY_TMP.PATH, HIERARCHY_TMP.PARENT, HIERARCHY_TMP.TYPE, HIERARCHY_TMP.SEQUENCE, HIERARCHY_TMP.NAME, HIERARCHY_TMP.PREFERRED_NAME
FROM  HIERARCHY_TMP;

#-- LINGUISTIC VARIANT
#\! echo '- Filling out ISO_COUNTRY & ISO_LANG of LIGUISTIC_VARIAN(S)...';
#UPDATE LINGUISTIC_VARIANT
#SET ISO_COUNTRY="KR", ISO_LANG="ko" 
#where SEQ < 26984;

#-- LINGUISTIC VARIANT
#UPDATE LINGUISTIC_VARIANT
#SET ISO_COUNTRY="CN", ISO_LANG="zh"
#where SEQ > 26983;

-- Panel
# version
#UPDATE PANEL
#SET VERSION="2.67";

# 1st PATH
#UPDATE PANEL as p1 JOIN
#(   SELECT ID, PARENT_ID, PARENT_CODE
#	FROM PANEL
#) as p2
#ON p1.PARENT_ID = p2.ID 
#SET p1.PATH=p2.PARENT_CODE;

# root setting
#UPDATE PANEL
#SET PARENT_CODE="ROOT", ROOT_CODE = CODE, PATH = CODE
#WHERE CODE = PARENT_CODE;

# root -> 1st code 
#UPDATE PANEL as p1 JOIN
#(   SELECT ID, ROOT_CODE
#	FROM PANEL
#	where PARENT_CODE = "ROOT" 
#) as p2
#ON p1.PARENT_ID = p2.ID 
#SET p1.ROOT_CODE = p2.ROOT_CODE;

# 1st PATH : code -> code
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE is null AND p1.PARENT_ID = p2.ID
#SET p1.PATH=CONCAT(p1.PATH, "~", p2.CODE), p1.ROOT_CODE = p2.PARENT_ID  ;

# ROOT_CODE : ID -> CODE
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_CODE
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
#SET p1.ROOT_CODE = p2.CODE;

# 2nd PATH : code -> code
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID
#SET p1.PATH=CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -1)), p1.ROOT_CODE = p2.PARENT_ID  ;

# ROOT_CODE : ID -> CODE
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_CODE
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
#SET p1.ROOT_CODE = p2.CODE, p1.PATH = CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -2));

# 3rd PATH : code -> code
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID
#SET p1.PATH=CONCAT(p2.CODE, "~", p1.PATH), p1.ROOT_CODE = p2.PARENT_ID  ;

# ROOT_CODE : ID -> CODE
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_CODE
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
#SET p1.ROOT_CODE = p2.CODE, p1.PATH = CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -3));

# 4rd PATH : code -> code
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID
#SET p1.PATH=CONCAT(p2.CODE, "~", p1.PATH), p1.ROOT_CODE = p2.PARENT_ID  ;

# ROOT_CODE : ID -> CODE
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_CODE
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
#SET p1.ROOT_CODE = p2.CODE, p1.PATH = CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -4));

# 5rd PATH : code -> code
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID
#SET p1.PATH=CONCAT(p2.CODE, "~", p1.PATH), p1.ROOT_CODE = p2.PARENT_ID  ;

# ROOT_CODE : ID -> CODE
#UPDATE PANEL as p1 JOIN
#(	SELECT ID, CODE, PARENT_CODE
#	FROM PANEL
#) as p2
#ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
#SET p1.ROOT_CODE = p2.CODE, p1.PATH = CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -5));

