USE loinc;


\! echo "additional3";

-- Panel
# version
UPDATE PANEL
SET VERSION="2.82";

# 1st PATH
\! echo '- Processing 1st PATH ...';
UPDATE PANEL as p1, 
(   SELECT ID, PARENT_CODE
    FROM PANEL
    GROUP BY ID
) as p2
SET p1.PATH=p2.PARENT_CODE
WHERE p1.PARENT_ID = p2.ID;

# root setting
\! echo '- Setting PARENT_CODE as "ROOT"...';
UPDATE PANEL
SET PARENT_CODE="ROOT", ROOT_CODE = CODE, PATH = CODE
WHERE CODE = PARENT_CODE;

# root -> 1st code
\! echo '- Setting PARENT_ID as ROOT ID ...';
UPDATE PANEL as p1 JOIN
(   SELECT ID, ROOT_CODE
    FROM PANEL
    where PARENT_CODE = "ROOT"
) as p2
ON p1.PARENT_ID = p2.ID
SET p1.ROOT_CODE = p2.ROOT_CODE;

# 1st PATH : code -> code
\! echo '- Concatenating PATH ...';
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
    FROM PANEL
) as p2
ON p1.ROOT_CODE is null AND p1.PARENT_ID = p2.ID
SET p1.PATH=CONCAT(p1.PATH, "~", p2.CODE), p1.ROOT_CODE = p2.PARENT_ID  ;

# ROOT_CODE : ID -> CODE
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_CODE
    FROM PANEL
) as p2
ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
SET p1.ROOT_CODE = p2.CODE;

select '- Processing 2nd PATH' as '';
# 2nd PATH : code -> code
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
    FROM PANEL
) as p2
ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID
SET p1.PATH=CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -1)), p1.ROOT_CODE = p2.PARENT_ID  ;


# ROOT_CODE : ID -> CODE
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_CODE
    FROM PANEL
) as p2
ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
SET p1.ROOT_CODE = p2.CODE, p1.PATH = CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -2));

select '- Processing 3rd PATH' as '';
# 3rd PATH : code -> code
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
    FROM PANEL
) as p2
ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID
SET p1.PATH=CONCAT(p2.CODE, "~", p1.PATH), p1.ROOT_CODE = p2.PARENT_ID  ;

# ROOT_CODE : ID -> CODE
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_CODE
    FROM PANEL
) as p2
ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
SET p1.ROOT_CODE = p2.CODE, p1.PATH = CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -3));


select '- Processing 4th PATH' as '';
# 4rd PATH : code -> code
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
    FROM PANEL
) as p2
ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID
SET p1.PATH=CONCAT(p2.CODE, "~", p1.PATH), p1.ROOT_CODE = p2.PARENT_ID  ;

# ROOT_CODE : ID -> CODE
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_CODE
    FROM PANEL
) as p2
ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
SET p1.ROOT_CODE = p2.CODE, p1.PATH = CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -4));

select '- Processing 5th PATH' as '';
# 5rd PATH : code -> code
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_ID, ROOT_CODE, PATH
    FROM PANEL
) as p2
ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID
SET p1.PATH=CONCAT(p2.CODE, "~", p1.PATH), p1.ROOT_CODE = p2.PARENT_ID  ;

# ROOT_CODE : ID -> CODE
UPDATE PANEL as p1 JOIN
(   SELECT ID, CODE, PARENT_CODE
    FROM PANEL
) as p2
ON p1.ROOT_CODE NOT LIKE '%-%' AND p1.ROOT_CODE = p2.ID AND p2.PARENT_CODE = "ROOT"
SET p1.ROOT_CODE = p2.CODE, p1.PATH = CONCAT(p2.CODE, "~", SUBSTRING_INDEX(p1.PATH, "~", -5));
