#DROP SCHEMA IF EXISTS loinc;
#CREATE SCHEMA loinc;
USE loinc;

### LOINC DDL

#### LOINC
DROP  TABLE IF EXISTS LOINC;
CREATE TABLE LOINC (
  CODE varchar(10) NOT NULL,
  COMPONENT varchar(255) DEFAULT NULL,
  PROPERTY varchar(30) DEFAULT NULL,
  TIME_ASPECT varchar(15) DEFAULT NULL,
  SYSTEM varchar(100) DEFAULT NULL,
  SCALE_TYPE varchar(30) DEFAULT NULL,
  METHOD_TYPE varchar(50) DEFAULT NULL,

  CLASS_NAME varchar(20) DEFAULT NULL,

  LAST_CHANGED_VERSION varchar(10) DEFAULT NULL,
  CHANGE_TYPE varchar(3) DEFAULT NULL,
  DEFINITION_DESCRIPTION text,
  STATUS varchar(11) DEFAULT NULL,
  CONSUMER_NAME varchar(255) DEFAULT NULL,
  CLASS_TYPE int(11) DEFAULT NULL,
  FORMULA text,

  EXAMPLE_ANSWERS text,
  SURVEY_QUEST_TEXT text,
  SURVEY_QUEST_SRC varchar(50) DEFAULT NULL,
  UNITS_REQUIRED varchar(1) DEFAULT NULL,
  SUBMITTED_UNITS varchar(30) DEFAULT NULL,
  RELATED_NAMES2 text,

  SHORT_NAME varchar(40) DEFAULT NULL,
  ORDER_OBS varchar(15) DEFAULT NULL,
  CDISC_COMMON_TESTS varchar(1) DEFAULT NULL,
  HL7_FIELD_SUBFIELD_ID varchar(50) DEFAULT NULL,
  EXTERNAL_COPYRIGHT_NOTICE text,
  EXAMPLE_UNITS varchar(255) DEFAULT NULL,
  LONG_COMMON_NAME varchar(255) DEFAULT NULL,
  UNITS_AND_RANGE text,
  EXAMPLE_UCUM_UNITS varchar(255) DEFAULT NULL,
  EXAMPLE_SI_UCUM_UNITS varchar(255) DEFAULT NULL,
  STATUS_REASON varchar(9) DEFAULT NULL,
  STATUS_TEXT text,
  CHANGE_REASON_PUBLIC text,
  COMMON_TEST_RANK int(11) DEFAULT NULL,
  COMMON_ORDER_RANK int(11) DEFAULT NULL,
  COMMON_SI_TEST_RANK int(11) DEFAULT NULL,
  HL7_ATTACHMENT_STRUCTURE varchar(15) DEFAULT NULL,
  EXTERNAL_COPYRIGHT_LINK varchar(255) DEFAULT NULL,
  PANEL_TYPE varchar(255) DEFAULT NULL,
  ASK_AT_ORDER_ENTRY varchar(255) DEFAULT NULL,
  ASSOCIATED_OBSERVATIONS varchar(50) DEFAULT NULL,
  FIRST_RELEASED_VERSION varchar(255) DEFAULT NULL,
  VALID_HL7_ATTACHMENT_REQUEST varchar(255) DEFAULT NULL,
  DISPLAY_NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#### Map To
DROP  TABLE IF EXISTS MAP_TO;
CREATE TABLE MAP_TO (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  CODE varchar(10) DEFAULT NULL,
  MAP_TO varchar(10) DEFAULT NULL,
  COMMENT text,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#### Source Organization
DROP  TABLE IF EXISTS SOURCE_ORGANIZATION;
CREATE TABLE SOURCE_ORGANIZATION (
  ID bigint(20) NOT NULL,
  COPYRIGHT_ID varchar(255) DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  COPYRIGHT text,
  TERMS_OF_USE text,
  URL varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#### Hierarchy
DROP  TABLE IF EXISTS HIERARCHY;
CREATE TABLE HIERARCHY (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  CHILDREN_COUNT int(11) DEFAULT 0,
  CODE varchar(50) DEFAULT NULL,
  DESCENDANT_COUNT int(11) DEFAULT 0,
  NAME varchar(255) DEFAULT NULL,
  PARENT varchar(255) DEFAULT NULL,
  PATH varchar(255) DEFAULT NULL,
  PREFERRED_NAME text,
  SEQUENCE int(11) DEFAULT NULL,
  TYPE int(11) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY `IDX_CODE` (`CODE`),
  KEY `IDX_PARENT` (`PARENT`),
  KEY `IDX_PATH` (`PATH`),
  KEY `IDX_CHILDREN` (`CHILDREN_COUNT`),
  KEY `IDX_DESCENDANT` (`DESCENDANT_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#### Hierarchy tmp
DROP  TABLE IF EXISTS HIERARCHY_TMP;
CREATE TABLE HIERARCHY_TMP (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  CHILDREN_COUNT int(11) DEFAULT 0,
  CODE varchar(50) DEFAULT NULL,
  DESCENDANT_COUNT int(11) DEFAULT 0,
  NAME varchar(255) DEFAULT NULL,
  PARENT varchar(255) DEFAULT NULL,
  PATH varchar(255) DEFAULT NULL,
  PREFERRED_NAME text,
  SEQUENCE int(11) DEFAULT NULL,
  TYPE int(11) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY `IDX_CODE` (`CODE`),
  KEY `IDX_PARENT` (`PARENT`),
  KEY `IDX_PATH` (`PATH`),
  KEY `IDX_CHILDREN` (`CHILDREN_COUNT`),
  KEY `IDX_DESCENDANT` (`DESCENDANT_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#### Hierarchy LG
DROP  TABLE IF EXISTS HIERARCHY_LG;
CREATE TABLE HIERARCHY_LG (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  CHILDREN_COUNT int(11) DEFAULT 0,
  CODE varchar(50) DEFAULT NULL,
  DESCENDANT_COUNT int(11) DEFAULT 0,
  NAME varchar(255) DEFAULT NULL,
  PARENT varchar(255) DEFAULT NULL,
  PATH varchar(255) DEFAULT NULL,
  PREFERRED_NAME text,
  SEQUENCE int(11) DEFAULT NULL,
  TYPE int(11) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY `IDX_CODE` (`CODE`),
  KEY `IDX_PARENT` (`PARENT`),
  KEY `IDX_PATH` (`PATH`),
  KEY `IDX_CHILDREN` (`CHILDREN_COUNT`),
  KEY `IDX_DESCENDANT` (`DESCENDANT_COUNT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#### Linguistic Variant
DROP  TABLE IF EXISTS LINGUISTIC_VARIANT;
CREATE TABLE LINGUISTIC_VARIANT (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  CODE varchar(10) DEFAULT NULL,
  COMPONENT varchar(255) DEFAULT NULL,
  PROPERTY varchar(30) DEFAULT NULL,
  TIME_ASPECT varchar(15) DEFAULT NULL,
  SYSTEM varchar(100) DEFAULT NULL,
  SCALE_TYPE varchar(30) DEFAULT NULL,
  METHOD_TYPE varchar(50) DEFAULT NULL,
  CLASS_NAME varchar(40) DEFAULT NULL,
  SHORT_NAME varchar(40) DEFAULT NULL,
  LONG_COMMON_NAME varchar(255) DEFAULT NULL,
  ISO_COUNTRY varchar(2) DEFAULT NULL,
  ISO_LANG varchar(2) DEFAULT NULL,
  RELATED_NAMES2 text,
  LANG varchar(30) DEFAULT NULL,
  PRIMARY KEY (SEQ),
  KEY LANG (CODE,ISO_LANG,ISO_COUNTRY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#### Linguistic Variants
DROP  TABLE IF EXISTS LINGUISTIC_VARIANTS;
CREATE TABLE LINGUISTIC_VARIANTS (
  SEQ bigint(20) NOT NULL AUTO_INCREMENT,
  ID VARCHAR(2) DEFAULT NULL,
  ISO_LANG varchar(2) DEFAULT NULL,
  ISO_COUNTRY varchar(2) DEFAULT NULL,
  LANG varchar(30) DEFAULT NULL,
  PRODUCER text,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC Part의 계층구조를 관리하는 테이블
#DROP TABLE IF EXISTS MULTIAXIAL_HIERARCHY;
#CREATE TABLE MULTIAXIAL_HIERARCHY (
#  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
#  PATH_TO_ROOT VARCHAR(4000) DEFAULT NULL,
#  SEQUENCE DECIMAL(10,0) DEFAULT NULL,
#  IMMEDIATE_PARENT VARCHAR(255) DEFAULT NULL,
#  CODE VARCHAR(255) DEFAULT NULL,
#  CODE_TEXT VARCHAR(255) DEFAULT NULL,
#  PRIMARY KEY (SEQ),
#  KEY IDX_CODE (CODE) USING BTREE
#) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC Propery 목록을 관리하는 테이블
#DROP  TABLE IF EXISTS PROPERTY;
#CREATE TABLE PROPERTY (
#  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
#  CATEGORY VARCHAR(60) DEFAULT NULL, -- Mass, Substance, Catalytic activity, Arbitrary, Number
#  VALUE VARCHAR(20) NOT NULL, --
#  DESCRIPTION VARCHAR(255) DEFAULT NULL,
#  PRIMARY KEY (SEQ)
#) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC Class 목록을 관리하는 테이블
DROP  TABLE IF EXISTS CLASS;
CREATE TABLE CLASS (
  SEQ INT(4) NOT NULL AUTO_INCREMENT,
  TYPE INT(2) NOT NULL,
  NAME VARCHAR(20) NOT NULL, --
  ABBREVIATION VARCHAR(255) NOT NULL,
  TERM VARCHAR(255) NOT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC Panel 목록을 관리하는 테이블
DROP  TABLE IF EXISTS PANEL;
CREATE TABLE PANEL (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  VERSION VARCHAR(4) DEFAULT NULL,
  PATH VARCHAR(255) DEFAULT NULL,
  ROOT_CODE VARCHAR(10) DEFAULT NULL,
  PARENT_ID VARCHAR(10) DEFAULT NULL,
  PARENT_CODE VARCHAR(10) DEFAULT NULL,
  PARENT_NAME VARCHAR(255) DEFAULT NULL,
  ID VARCHAR(11) DEFAULT NULL,
  SEQUENCE INT(11) DEFAULT NULL,
  CODE VARCHAR(10) DEFAULT NULL,
  NAME VARCHAR(255) DEFAULT NULL,
  DISPLAY_NAME_FOR_FORM VARCHAR(255) DEFAULT NULL,
  OBSERVATION_REQUIRED_IN_PANEL VARCHAR(255) DEFAULT NULL,
  OBSERVATION_ID_IN_FORM VARCHAR(10) DEFAULT NULL,
  SKIP_LOGIC_HELP_TEXT VARCHAR(255) DEFAULT NULL,
  DEFAULT_VALUE VARCHAR(20) DEFAULT NULL,
  ENTRY_TYPE VARCHAR(10) DEFAULT NULL,
  DATA_TYPE_IN_FORM VARCHAR(10) DEFAULT NULL,
  DATA_TYPE_SOURCE VARCHAR(255) DEFAULT NULL,
  ANSWER_SEQUENCE_OVERRIDE VARCHAR(255) DEFAULT NULL,
  CONDITION_FOR_INCLUSION VARCHAR(255) DEFAULT NULL,
  ALLOWABLE_ALTERNATIVE VARCHAR(255) DEFAULT NULL,
  OBSERVATION_CATEGORY VARCHAR(20) DEFAULT NULL,
  CONTEXT text,
  CONSISTENCY_CHECKS VARCHAR(255) DEFAULT NULL,
  RELEVANCE_EQUATION VARCHAR(255) DEFAULT NULL,
  CODING_INSTRUCTIONS VARCHAR(255) DEFAULT NULL,
  QUESTION_CARDINALITY VARCHAR(10) DEFAULT NULL,
  ANSWER_CARDINALITY VARCHAR(10) DEFAULT NULL,
  ANSWER_LIST_ID_OVERRIDE VARCHAR(10) DEFAULT NULL,
  ANSWER_LIST_TYPE_OVERRIDE VARCHAR(10) DEFAULT NULL,
  EXTERNAL_COPYRIGHT_NOTICE text,
  PRIMARY KEY (SEQ),
  KEY `IDX_CODE` (`CODE`),
  KEY `IDX_ID` (`ID`),
  KEY `IDX_PARENT_ID` (`PARENT_ID`),
  KEY `IDX_PARENT_NAME` (`PARENT_NAME`),
  KEY `IDX_PARENT_CODE` (`PARENT_CODE`),
  KEY `IDX_PATH` (`PATH`),
  KEY `IDX_ROOT_CODE` (`ROOT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC LP 목록을 관리하는 테이블
DROP  TABLE IF EXISTS LP;
CREATE TABLE LP (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  PART_NUMBER VARCHAR(10) DEFAULT NULL,
  PART_TYPE_NAME VARCHAR(20) DEFAULT NULL,
  PART_NAME VARCHAR(255) DEFAULT NULL,
  PART_DISPLAY_NAME VARCHAR(255) DEFAULT NULL,
  STATUS VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC LP LINK 테이블
DROP  TABLE IF EXISTS LP_LINK;
CREATE TABLE LP_LINK (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  LOINC_NUMBER VARCHAR(10) NOT NULL,
  LONG_COMMON_NAME VARCHAR(255) DEFAULT NULL,
  PART_NUMBER VARCHAR(10) NOT NULL,
  PART_NAME VARCHAR(255) NOT NULL,
  PART_CODE_SYSTEM VARCHAR(255) NOT NULL,
  PART_TYPE_NAME VARCHAR(20) NOT NULL,
  LINK_TYPE_NAME VARCHAR(20) NOT NULL,
  PROPERTY VARCHAR(255) NOT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC LP Related Code Mapping 테이블
DROP  TABLE IF EXISTS LP_MAP;
CREATE TABLE LP_MAP (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  PART_NUMBER VARCHAR(10) DEFAULT NULL,
  PART_NAME VARCHAR(255) DEFAULT NULL,
  PART_TYPE_NAME VARCHAR(20) DEFAULT NULL,
  EXT_CODE_ID VARCHAR(20) DEFAULT NULL,
  EXT_CODE_DISPLAY_NAME VARCHAR(255) DEFAULT NULL,
  EXT_CODE_SYSTEM VARCHAR(50) DEFAULT NULL,
  EQUIVALENCE VARCHAR(20) DEFAULT NULL,
  CONTENT_ORIGIN VARCHAR(20) DEFAULT NULL,
  EXT_CODE_SYSTEM_VERSION VARCHAR(100) DEFAULT NULL,
  EXT_CODE_SYSTEM_COPYRIGHT_NOTICE VARCHAR(1024) DEFAULT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC ANSWER LIST 테이블 
DROP  TABLE IF EXISTS LA;
CREATE TABLE LA (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  ANSWER_LIST_ID VARCHAR(10) NOT NULL, 
  ANSWER_LIST_NAME VARCHAR(255) NOT NULL, 
  ANSWER_LIST_OID VARCHAR(255) DEFAULT NULL, 
  EXT_DEFINED_YN VARCHAR(1) DEFAULT NULL, 
  EXT_DEFINED_ANSWER_LIST_CODE_SYSTEM VARCHAR(255) DEFAULT NULL, 
  EXT_DEFINED_ANSWER_LIST_LINK VARCHAR(255) DEFAULT NULL, 
  ANSWER_STRING_ID VARCHAR(10) NOT NULL, 
  LOCAL_ANSWER_CODE VARCHAR(3) NOT  NULL, 
  LOCAL_ANSWER_CODE_SYSTEM VARCHAR(255) DEFAULT NULL, 
  SEQUENCE_NUMBER INT(3) NOT NULL, 
  DISPLAY_TEXT VARCHAR(255) DEFAULT NULL, 
  EXT_CODE_ID VARCHAR(20) DEFAULT NULL, 
  EXT_CODE_DISPLAY_NAME VARCHAR(255) DEFAULT NULL, 
  EXT_CODE_SYSTEM VARCHAR(255) DEFAULT NULL, 
  EXT_CODE_SYSTEM_VERSION VARCHAR(255) DEFAULT NULL, 
  EXT_CODE_SYSTEM_COPYRIGHT_NOTICE text, 
  SUBSEQUENCE_TEXT_PROMPT VARCHAR(255) DEFAULT NULL, 
  DESCRIPTION text, 
  SCORE VARCHAR(3) DEFAULT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC ANSWER LIST 테이블
DROP  TABLE IF EXISTS LA_LINK;
CREATE TABLE LA_LINK (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  LOINC_NUMBER VARCHAR(10) NOT NULL, 
  LONG_COMMON_NAME varchar(255) NOT NULL, 
  ANSWER_LIST_ID varchar(10) NOT NULL,  
  ANSWER_LIST_NAME varchar(255) NOT NULL, 
  ANSWER_LIST_LINK_TYPE varchar(20) NOT NULL, 
  APPLICABLE_CONTEXT varchar(255) DEFAULT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC Group 테이블
DROP  TABLE IF EXISTS PARENT_LG;
CREATE TABLE PARENT_LG (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  PARENT_LG_ID VARCHAR(10) NOT NULL,
  PARENT_LG varchar(255) NOT NULL,
  STATUS varchar(10) NOT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC Group 테이블
DROP  TABLE IF EXISTS PARENT_LG_ATTRIBUTES;
CREATE TABLE PARENT_LG_ATTRIBUTES (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  PARENT_LG_ID VARCHAR(10) NOT NULL,
  TYPE varchar(50) NOT NULL,
  VALUE varchar(255) NOT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC Group 테이블
DROP  TABLE IF EXISTS LG;
CREATE TABLE LG (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  PARENT_LG_ID VARCHAR(10) NOT NULL,
  LG_ID varchar(10) NOT NULL,
  LG varchar(255) NOT NULL,
  ARCHETYPE varchar(10) DEFAULT NULL,
  STATUS varchar(10) DEFAULT NULL,
  VERSION_FIRST_RELEASED varchar(8) DEFAULT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC Group 테이블
DROP  TABLE IF EXISTS LG_ATTRIBUTES;
CREATE TABLE LG_ATTRIBUTES (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  PARENT_LG_ID VARCHAR(10) NOT NULL,
  LG_ID varchar(10) NOT NULL,
  TYPE varchar(50) NOT NULL,
  VALUE varchar(255) NOT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

# LOINC Group 테이블
DROP  TABLE IF EXISTS LG_TERMS;
CREATE TABLE LG_TERMS (
  SEQ BIGINT(20) NOT NULL AUTO_INCREMENT,
  CATEGORY VARCHAR(50) NOT NULL,
  LG_ID varchar(10) NOT NULL,
  ARCHETYPE varchar(10) DEFAULT NULL,
  LOINC_NUMBER varchar(10) NOT  NULL,
  LONG_COMMON_NAME varchar(255) DEFAULT NULL,
  LG_ID_NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

quit
