USE loinc;

#### LOINC
DROP  TABLE IF EXISTS LOINC;
CREATE TABLE LOINC (
  CODE varchar(10) NOT NULL,
  COMPONENT varchar(255) DEFAULT NULL,
  PROPERTY varchar(30) DEFAULT NULL,
  TIME_ASPECT varchar(15) DEFAULT NULL,
  SYSTEM varchar(100) DEFAULT NULL,
  SCALE_TYPE varchar(30) DEFAULT NULL,
  METHOD_TYPE varchar(50) DEFAULT NULL,

  CLASS_NAME varchar(20) DEFAULT NULL,

  LAST_CHANGED_VERSION varchar(10) DEFAULT NULL,
  CHANGE_TYPE varchar(3) DEFAULT NULL,
  DEFINITION_DESCRIPTION text,
  STATUS varchar(11) DEFAULT NULL,
  CONSUMER_NAME varchar(255) DEFAULT NULL,
  CLASS_TYPE int(11) DEFAULT NULL,
  FORMULA text,

  EXAMPLE_ANSWERS text,
  SURVEY_QUEST_TEXT text,
  SURVEY_QUEST_SRC varchar(50) DEFAULT NULL,
  UNITS_REQUIRED varchar(1) DEFAULT NULL,
  SUBMITTED_UNITS varchar(30) DEFAULT NULL,
  RELATED_NAMES2 text,

  SHORT_NAME varchar(40) DEFAULT NULL,
  ORDER_OBS varchar(15) DEFAULT NULL,
  CDISC_COMMON_TESTS varchar(1) DEFAULT NULL,
  HL7_FIELD_SUBFIELD_ID varchar(50) DEFAULT NULL,
  EXTERNAL_COPYRIGHT_NOTICE text,
  EXAMPLE_UNITS varchar(255) DEFAULT NULL,
  LONG_COMMON_NAME varchar(255) DEFAULT NULL,
  UNITS_AND_RANGE text,
  EXAMPLE_UCUM_UNITS varchar(255) DEFAULT NULL,
  EXAMPLE_SI_UCUM_UNITS varchar(255) DEFAULT NULL,
  STATUS_REASON varchar(9) DEFAULT NULL,
  STATUS_TEXT text,
  CHANGE_REASON_PUBLIC text,
  COMMON_TEST_RANK int(11) DEFAULT NULL,
  COMMON_ORDER_RANK int(11) DEFAULT NULL,
  COMMON_SI_TEST_RANK int(11) DEFAULT NULL,
  HL7_ATTACHMENT_STRUCTURE varchar(15) DEFAULT NULL,
  EXTERNAL_COPYRIGHT_LINK varchar(255) DEFAULT NULL,
  PANEL_TYPE varchar(255) DEFAULT NULL,
  ASK_AT_ORDER_ENTRY varchar(255) DEFAULT NULL,
  ASSOCIATED_OBSERVATIONS varchar(50) DEFAULT NULL,
  FIRST_RELEASED_VERSION varchar(255) DEFAULT NULL,
  VALID_HL7_ATTACHMENT_REQUEST varchar(255) DEFAULT NULL,
  DISPLAY_NAME varchar(255) DEFAULT NULL,
  PRIMARY KEY (CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

