--
-- LOINC MySql load script.
--
-- http://dev.mysql.com/doc/refman/5.6/en/load-data.html
--

USE loinc;

#### LinguaiticVariants Table
\! echo 'Loading LINGUISTIC_VARIANTS Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/LinguisticVariants.csv'
INTO TABLE LINGUISTIC_VARIANTS
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( ID, ISO_LANG, ISO_COUNTRY, LANG, PRODUCER );

#### LinguisticVariant Table (deCH)
#\! echo 'Loading LINGUISTIC_VARIANT(deCH) Table';
#LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/deCH1LinguisticVariant.csv'
#INTO TABLE LINGUISTIC_VARIANT
#FIELDS TERMINATED BY ','
#OPTIONALLY ENCLOSED BY '"'
#LINES TERMINATED BY '\r\n'
#IGNORE 1 LINES

#( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

#SET ISO_COUNTRY = 'CH', ISO_LANG = 'de';

#### LinguisticVariant Table (frCH)
#\! echo 'Loading LINGUISTIC_VARIANT(frCH) Table';
#LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/Loinc_2.68/AccessoryFiles/Loinc_2/frCH2LinguisticVariant.csv'
#INTO TABLE LINGUISTIC_VARIANT
#FIELDS TERMINATED BY ','
#OPTIONALLY ENCLOSED BY '"'
#LINES TERMINATED BY '\r\n'
#IGNORE 1 LINES

#( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

#SET ISO_COUNTRY = 'CH', ISO_LANG = 'fr';

#### LinguisticVariant Table (itCH)
#\! echo 'Loading LINGUISTIC_VARIANT(itCH) Table';
#LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/itCH3LinguisticVariant.csv'
#INTO TABLE LINGUISTIC_VARIANT
#FIELDS TERMINATED BY ','
#OPTIONALLY ENCLOSED BY '"'
#LINES TERMINATED BY '\r\n'
#IGNORE 1 LINES

#( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

#SET ISO_COUNTRY = 'CH', ISO_LANG = 'it';

#### LinguisticVariant Table (esCH)
#\! echo 'Loading LINGUISTIC_VARIANT(esCH) Table';
#LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/esCH4LinguisticVariant.csv'
#INTO TABLE LINGUISTIC_VARIANT
#FIELDS TERMINATED BY ','
#OPTIONALLY ENCLOSED BY '"'
#LINES TERMINATED BY '\r\n'
#IGNORE 1 LINES

#( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

#SET ISO_COUNTRY = 'CH', ISO_LANG = 'es';

#### LinguisticVariant Table (zhCNi5)
\! echo 'Loading LINGUISTIC_VARIANT(zhCN5) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/zhCN5LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'CN', ISO_LANG = 'zh';

#### LinguisticVariant Table (esAR7)
\! echo 'Loading LINGUISTIC_VARIANT(esAR7) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/esAR7LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 ) 

SET ISO_COUNTRY = 'AR', ISO_LANG = 'es';

#### LinguisticVariant Table (frCA8)
\! echo 'Loading LINGUISTIC_VARIANT(frCA8) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/frCA8LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'CA', ISO_LANG = 'fr';

#### LinguisticVariant Table (etEE10)
\! echo 'Loading LINGUISTIC_VARIANT(etEE10) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/etEE10LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'EE', ISO_LANG = 'et';

#### LinguisticVariant Table (ptBR11)
\! echo 'Loading LINGUISTIC_VARIANT(ptBR11) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/ptBR11LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'BR', ISO_LANG = 'pt';

#### LinguisticVariant Table (esES12)
\! echo 'Loading LINGUISTIC_VARIANT(esES12) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/esES12LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'ES', ISO_LANG = 'es';


#### LinguisticVariant Table (koKR13)
\! echo 'Loading LINGUISTIC_VARIANT(koKR13) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/koKR13LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'KR', ISO_LANG = 'ko';

#### LinguisticVariant Table (deDE15)
\! echo 'Loading LINGUISTIC_VARIANT(deDE15) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/deDE15LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'DE', ISO_LANG = 'de';

#### LinguisticVariant Table (itIT16)
\! echo 'Loading LINGUISTIC_VARIANT(itIT16) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/itIT16LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'IT', ISO_LANG = 'it';

#### LinguisticVariant Table (elGR17)
\! echo 'Loading LINGUISTIC_VARIANT(elGR17) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/elGR17LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'GR', ISO_LANG = 'el';

#### LinguisticVariant Table (frFR18)
\! echo 'Loading LINGUISTIC_VARIANT(frFR18) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/frFR18LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'FR', ISO_LANG = 'fr';

#### LinguisticVariant Table (trTR19)
\! echo 'Loading LINGUISTIC_VARIANT(trTR19) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/trTR19LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'TR', ISO_LANG = 'tr';

#### LinguisticVariant Table (ruRU20)
\! echo 'Loading LINGUISTIC_VARIANT(ruRU20) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/ruRU20LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'RU', ISO_LANG = 'ru';

#### LinguisticVariant Table (nlNL22)
\! echo 'Loading LINGUISTIC_VARIANT(nlNL22) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/nlNL22LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'NL', ISO_LANG = 'nl';

#### LinguisticVariant Table (frBE23)
\! echo 'Loading LINGUISTIC_VARIANT(frBE23) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/frBE23LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'BE', ISO_LANG = 'fr';

#### LinguisticVariant Table (deAT24)
\! echo 'Loading LINGUISTIC_VARIANT(deAT24) Table';
LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.68/AccessoryFiles/Loinc_2/deAT24LinguisticVariant.csv'
INTO TABLE LINGUISTIC_VARIANT
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES

( CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM, SCALE_TYPE, METHOD_TYPE, CLASS_NAME, SHORT_NAME, LONG_COMMON_NAME, RELATED_NAMES2 )

SET ISO_COUNTRY = 'AT', ISO_LANG = 'de';

