use loinc;

# add HIERARCHY_LG to HIERARCHY
\! echo '- Transfer HIERARCHY_LG to HIERARCHY...';
INSERT INTO HIERARCHY (CHILDREN_COUNT, CODE, DESCENDANT_COUNT, PATH, PARENT, TYPE, SEQUENCE, NAME, PREFERRED_NAME)
SELECT lg.CHILDREN_COUNT, lg.CODE, lg.DESCENDANT_COUNT, lg.PATH, lg.PARENT, lg.TYPE, lg.SEQUENCE, lg.NAME, lg.PREFERRED_NAME
FROM  HIERARCHY_LG as lg;


quit

