USE loinc;

USE loinc;

\! echo 'Loading LOINC Table';
 LOAD DATA LOCAL INFILE '/home/devstudy/resources/release_files/loinc/LOINC_2.71/LoincTable/Loinc.csv'
 INTO TABLE LOINC
 FIELDS TERMINATED BY ','
 OPTIONALLY ENCLOSED BY '"'
 LINES TERMINATED BY '\r\n'
 IGNORE 1 LINES

 (
  CODE, COMPONENT, PROPERTY, TIME_ASPECT, SYSTEM,SCALE_TYPE,METHOD_TYPE,
  CLASS_NAME,
  LAST_CHANGED_VERSION,
  CHANGE_TYPE,
  DEFINITION_DESCRIPTION,
  STATUS,
  CONSUMER_NAME,
  CLASS_TYPE,
  FORMULA,
  EXAMPLE_ANSWERS,
  SURVEY_QUEST_TEXT,
  SURVEY_QUEST_SRC,
  UNITS_REQUIRED,
  SUBMITTED_UNITS,
  RELATED_NAMES2,
  SHORT_NAME,
  ORDER_OBS,
  CDISC_COMMON_TESTS,
  HL7_FIELD_SUBFIELD_ID,
  EXTERNAL_COPYRIGHT_NOTICE,
  EXAMPLE_UNITS,
  LONG_COMMON_NAME,
  UNITS_AND_RANGE,
  EXAMPLE_UCUM_UNITS,
  EXAMPLE_SI_UCUM_UNITS,
  STATUS_REASON,
  STATUS_TEXT,
  CHANGE_REASON_PUBLIC,
  COMMON_TEST_RANK,
  COMMON_ORDER_RANK,
  COMMON_SI_TEST_RANK,
  HL7_ATTACHMENT_STRUCTURE,
  EXTERNAL_COPYRIGHT_LINK,
  PANEL_TYPE,
  ASK_AT_ORDER_ENTRY,
  ASSOCIATED_OBSERVATIONS,
  FIRST_RELEASED_VERSION,
  VALID_HL7_ATTACHMENT_REQUEST,
  DISPLAY_NAME
 );


quit

