#----------------------------------------------------------------
# Logstash configufation file for ICD10 Search Index
# version 1, updated 20180325.
# copyright 2016 infoclinic co.,ltd, http://infoclinic.co
#----------------------------------------------------------------
input {
	stdin{}
#	file {
#		# 파일 경로
#		path => "/tmp/icd10_index.csv"
#		# 파일 읽기를 원하는 위치
#		start_position => "beginning"
#	}
}
# Logstash Filter
filter {
	# Logstash Plugin
	# csv: Parse comma-separated value data into individual fields
	csv {
		# setting
		# columns: csv파일 각 라인을 대상으로 왼쪽부터 순서대로 필드명을 입력한다. output에서 받고자하는 필드명을 작성한다.
		columns => ["code", "kind", "label"]
		# separator: csv파일 각 라인은 여러필드에 대한 데이터가 구분자로 구분되어져있다. 구분자를 작성한다.
		separator => "	"
	}
        mutate {
            # logstash를 이용해서 데이터를 보내면 기본적으로 붙는 필드들이 있다.
            # timestamp를 제외한 나머지 필드는 불필요하여 아래와 같이 제거한다.
            # usage: remove_field => ["{필드명}"]
            remove_field => ["path", "message", "host", "@version"]
            # 특수문자(special character)와 같이 검색에 불필요하거나 인덱싱에 방해되는 요소는 gsub으로 제거할 수 있다.
            # usage: gsub => ["{필드명}", "찾으려는 문자(regex syntax로 입력)", "변경되는 문자"]
	    gsub => ["label","\"",""]
	    gsub => ["label","<sub>",""]
	    gsub => ["label","</sub>",""]
	    gsub => ["label","<span style=\"font-weight:bold\">",""]
	    gsub => ["label","<span style=\"font-style:italic\">",""]
	    gsub => ["label","<span style=\"font-weight:bold\">",""]
	    gsub => ["label","</span>",""]
	    gsub => ["label","<ul>",""]
            gsub => ["label","</ul>",""]
            gsub => ["label","<ol type=\"a\">",""]
            gsub => ["label","</ol",""]
            gsub => ["label","<li>",""]
	    gsub => ["label","</li>",""]
	    gsub => ["label","<THead>",""]
	    gsub => ["label","</THead>",""]
	    gsub => ["label","<TBody>",""]
	    gsub => ["label","</TBody>",""]
	    gsub => ["label","<Table>",""]
	    gsub => ["label","</Table>",""]
	    gsub => ["label","<tr>",""]
	    gsub => ["label","</tr>",""]
	    gsub => ["label","<td>",""]
	    gsub => ["label","</td>",""]
	}
}
output {
	elasticsearch {
		index => "icd10_2016"
		document_type => "term_icd10_type"
		hosts => ["localhost:19210"]
		user => "ic_admin"
		password => "infoclinic2!"
		flush_size => 20000
	}
}
