package co.infoclinic.term.common.loader;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/**
 * Loads SNOMED CT RF2 release files from a ZIP archive into the PostgreSQL schema used by this project.
 * This utility focuses on the core tables used by the browser: CONCEPT, DESCRIPTION_TP,
 * INFERRED_RELATIONSHIP and STATED_RELATIONSHIP.
 */
public class SnomedRf2Loader {

    private static final String JDBC_URL = "jdbc:postgresql://localhost:5432/postgres";
    private static final String JDBC_USER = "postgres";
    private static final String JDBC_PASSWORD = "julab123!";

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            System.err.println("Usage: SnomedRf2Loader <path-to-snomed-rf2.zip>");
            System.exit(1);
        }

        Path zipPath = Paths.get(args[0]).toAbsolutePath().normalize();
        if (!zipPath.toFile().exists()) {
            throw new IllegalArgumentException("RF2 archive does not exist: " + zipPath);
        }

        System.out.println("Loading SNOMED RF2 archive: " + zipPath);

        try (Connection connection = DriverManager.getConnection(JDBC_URL, JDBC_USER, JDBC_PASSWORD)) {
            connection.setAutoCommit(false);
            try (Statement statement = connection.createStatement()) {
                statement.execute("SET search_path TO term, public");
            }

            ensureSchema(connection, zipPath);

            int conceptCount = 0;
            int descriptionCount = 0;
            int relationshipCount = 0;

            try (ZipInputStream zipStream = new ZipInputStream(new BufferedInputStream(new FileInputStream(zipPath.toFile())))) {
                ZipEntry entry;
                while ((entry = zipStream.getNextEntry()) != null) {
                    if (entry.isDirectory()) {
                        continue;
                    }

                    String entryName = entry.getName().toLowerCase(Locale.ROOT);
                    if (!entryName.endsWith(".txt")) {
                        continue;
                    }

                    byte[] entryBytes = readEntry(zipStream);
                    if (entryName.contains("sct2_concept_")) {
                        conceptCount += loadConcepts(connection, new ByteArrayInputStream(entryBytes));
                    } else if (entryName.contains("sct2_description_")) {
                        descriptionCount += loadDescriptions(connection, new ByteArrayInputStream(entryBytes));
                    } else if (entryName.contains("sct2_relationship_") || entryName.contains("sct2_statedrelationship_")) {
                        relationshipCount += loadRelationships(connection, new ByteArrayInputStream(entryBytes), entryName.contains("statedrelationship_"));
                    }
                }
            }

            connection.commit();
            System.out.println("Import finished. Concepts=" + conceptCount + ", Descriptions=" + descriptionCount
                    + ", Relationships=" + relationshipCount);
        }
    }

    private static void ensureSchema(Connection connection, Path zipPath) throws SQLException, IOException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("DROP SCHEMA IF EXISTS term CASCADE");
            statement.execute("CREATE SCHEMA IF NOT EXISTS term");
            statement.execute("SET search_path TO term, public");
            statement.execute("CREATE TABLE IF NOT EXISTS concept (" +
                    "SEQ BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "ACTIVE SMALLINT NOT NULL, " +
                    "EFFECTIVE_TIME CHAR(8) NOT NULL, " +
                    "MODULE_ID VARCHAR(18) NOT NULL, " +
                    "DEFINITION_STATUS_ID VARCHAR(18) NOT NULL, " +
                    "CONCEPT_ID VARCHAR(18) NOT NULL, " +
                    "DATE_CREATED TIMESTAMP DEFAULT NULL)");
            statement.execute("CREATE TABLE IF NOT EXISTS description_tp (" +
                    "SEQ BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "ACTIVE SMALLINT NOT NULL, " +
                    "EFFECTIVE_TIME CHAR(8) NOT NULL, " +
                    "MODULE_ID VARCHAR(18) NOT NULL, " +
                    "TYPE_ID VARCHAR(18) NOT NULL, " +
                    "CASE_SIGNIFICANCE_ID VARCHAR(18) NOT NULL, " +
                    "LANGUAGE_CODE CHAR(2) NOT NULL, " +
                    "LANGUAGE_CULTURE VARCHAR(5) DEFAULT NULL, " +
                    "TERM TEXT NOT NULL, " +
                    "CONCEPT_ID VARCHAR(18) NOT NULL, " +
                    "DESCRIPTION_ID VARCHAR(18) NOT NULL, " +
                    "CREATED_DATE TIMESTAMP DEFAULT NULL)");
            statement.execute("CREATE TABLE IF NOT EXISTS inferred_relationship (" +
                    "SEQ BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "ACTIVE SMALLINT NOT NULL, " +
                    "EFFECTIVE_TIME CHAR(8) NOT NULL, " +
                    "MODULE_ID VARCHAR(18) NOT NULL, " +
                    "SOURCE_ID VARCHAR(18) NOT NULL, " +
                    "DESTINATION_ID VARCHAR(18) NOT NULL, " +
                    "RELATIONSHIP_GROUP INTEGER NOT NULL, " +
                    "TYPE_ID VARCHAR(18) NOT NULL, " +
                    "CHARACTERISTIC_TYPE_ID VARCHAR(18) NOT NULL, " +
                    "MODIFIER_ID VARCHAR(18) NOT NULL, " +
                    "RELATIONSHIP_ID VARCHAR(18) NOT NULL)");
            statement.execute("CREATE TABLE IF NOT EXISTS stated_relationship (" +
                    "SEQ BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "ACTIVE SMALLINT NOT NULL, " +
                    "EFFECTIVE_TIME CHAR(8) NOT NULL, " +
                    "MODULE_ID VARCHAR(18) NOT NULL, " +
                    "SOURCE_ID VARCHAR(18) NOT NULL, " +
                    "DESTINATION_ID VARCHAR(18) NOT NULL, " +
                    "RELATIONSHIP_GROUP INTEGER NOT NULL, " +
                    "TYPE_ID VARCHAR(18) NOT NULL, " +
                    "CHARACTERISTIC_TYPE_ID VARCHAR(18) NOT NULL, " +
                    "MODIFIER_ID VARCHAR(18) NOT NULL, " +
                    "RELATIONSHIP_ID VARCHAR(18) NOT NULL)");
            statement.execute("CREATE TABLE IF NOT EXISTS scheme (" +
                    "ID VARCHAR(100) PRIMARY KEY, " +
                    "NAME VARCHAR(100) DEFAULT NULL, " +
                    "EDITION VARCHAR(100) DEFAULT NULL, " +
                    "VERSION VARCHAR(100) DEFAULT NULL)");
        }

        insertSchemeMetadata(connection, zipPath);
        connection.commit();
        System.out.println("Initialized the minimal SNOMED RF2 tables in PostgreSQL.");
    }

    private static void insertSchemeMetadata(Connection connection, Path zipPath) throws SQLException {
        String releaseDate = extractReleaseDate(zipPath);
        String id = "SNOMEDCT-v" + releaseDate;
        String name = "SNOMEDCT-Int";
        String edition = "SNOMEDCT v" + releaseDate;
        String version = "v" + releaseDate;

        String sql = "INSERT INTO scheme (ID, NAME, EDITION, VERSION) " +
                "VALUES (?, ?, ?, ?) " +
                "ON CONFLICT (ID) DO UPDATE SET " +
                "NAME = EXCLUDED.NAME, " +
                "EDITION = EXCLUDED.EDITION, " +
                "VERSION = EXCLUDED.VERSION";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, id);
            statement.setString(2, name);
            statement.setString(3, edition);
            statement.setString(4, version);
            statement.executeUpdate();
        }

        System.out.println("Initialized SCHEME metadata: ID=" + id + ", NAME=" + name + ", EDITION=" + edition + ", VERSION=" + version);
    }

    private static String extractReleaseDate(Path zipPath) {
        Matcher matcher = Pattern.compile("(\\d{8})").matcher(zipPath.getFileName().toString());
        if (matcher.find()) {
            return matcher.group(1);
        }
        return "20260601";
    }

    private static byte[] readEntry(ZipInputStream zipStream) throws IOException {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        byte[] chunk = new byte[8192];
        int read;
        while ((read = zipStream.read(chunk)) != -1) {
            buffer.write(chunk, 0, read);
        }
        return buffer.toByteArray();
    }

    private static int loadConcepts(Connection connection, InputStream inputStream) throws IOException, SQLException {
        String sql = "INSERT INTO concept (active, effective_time, module_id, definition_status_id, concept_id) "
                + "VALUES (?, ?, ?, ?, ?)";

        try (BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8));
             PreparedStatement statement = connection.prepareStatement(sql)) {

            String line;
            int count = 0;
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("id\t") || line.startsWith("effectiveTime\t") || line.trim().isEmpty()) {
                    continue;
                }

                String[] columns = line.split("\t", -1);
                if (columns.length < 5) {
                    continue;
                }

                statement.setInt(1, Integer.parseInt(columns[2]));
                statement.setString(2, columns[1]);
                statement.setString(3, columns[3]);
                statement.setString(4, columns[4]);
                statement.setString(5, columns[0]);

                statement.addBatch();
                count++;

                if (count % 1000 == 0) {
                    statement.executeBatch();
                }
            }

            if (count % 1000 != 0) {
                statement.executeBatch();
            }

            System.out.println("Loaded concepts: " + count);
            return count;
        }
    }

    private static int loadDescriptions(Connection connection, InputStream inputStream) throws IOException, SQLException {
        String sql = "INSERT INTO description_tp (active, effective_time, module_id, type_id, case_significance_id, "
                + "language_code, language_culture, term, concept_id, description_id) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8));
             PreparedStatement statement = connection.prepareStatement(sql)) {

            String line;
            int count = 0;
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("id\t") || line.startsWith("effectiveTime\t") || line.trim().isEmpty()) {
                    continue;
                }

                String[] columns = line.split("\t", -1);
                if (columns.length < 9) {
                    continue;
                }

                statement.setInt(1, Integer.parseInt(columns[2]));
                statement.setString(2, columns[1]);
                statement.setString(3, columns[3]);
                statement.setString(4, columns[6]);
                statement.setString(5, columns[8]);
                statement.setString(6, columns[5]);
                statement.setString(7, null);
                statement.setString(8, columns[7]);
                statement.setString(9, columns[4]);
                statement.setString(10, columns[0]);

                statement.addBatch();
                count++;

                if (count % 1000 == 0) {
                    statement.executeBatch();
                }
            }

            if (count % 1000 != 0) {
                statement.executeBatch();
            }

            System.out.println("Loaded descriptions: " + count);
            return count;
        }
    }

    private static int loadRelationships(Connection connection, InputStream inputStream, boolean stated) throws IOException, SQLException {
        String sql = stated
                ? "INSERT INTO stated_relationship (active, effective_time, module_id, source_id, destination_id, relationship_group, "
                + "type_id, characteristic_type_id, modifier_id, relationship_id) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
                : "INSERT INTO inferred_relationship (active, effective_time, module_id, source_id, destination_id, relationship_group, "
                + "type_id, characteristic_type_id, modifier_id, relationship_id) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8));
             PreparedStatement statement = connection.prepareStatement(sql)) {

            String line;
            int count = 0;
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("id\t") || line.startsWith("effectiveTime\t") || line.trim().isEmpty()) {
                    continue;
                }

                String[] columns = line.split("\t", -1);
                if (columns.length < 10) {
                    continue;
                }

                statement.setInt(1, Integer.parseInt(columns[2]));
                statement.setString(2, columns[1]);
                statement.setString(3, columns[3]);
                statement.setString(4, columns[4]);
                statement.setString(5, columns[5]);
                statement.setInt(6, Integer.parseInt(columns[6]));
                statement.setString(7, columns[7]);
                statement.setString(8, columns[8]);
                statement.setString(9, columns[9]);
                statement.setString(10, columns[0]);

                statement.addBatch();
                count++;

                if (count % 1000 == 0) {
                    statement.executeBatch();
                }
            }

            if (count % 1000 != 0) {
                statement.executeBatch();
            }

            System.out.println((stated ? "Loaded stated relationships" : "Loaded inferred relationships") + ": " + count);
            return count;
        }
    }
}
